import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const app = readFileSync('src/app.mjs', 'utf8');
const css = readFileSync('src/styles.css', 'utf8');
const html = readFileSync('index.html', 'utf8');

assert.match(app, /phase38-deals-empty/, 'Deals empty state must use the Phase 38 compact component.');
assert.match(app, /This lane is intentionally quiet\./, 'Deals empty state must explain intentional emptiness quickly.');
assert.match(app, /Why empty:/, 'Deals empty state must include a small why-empty explanation.');
assert.match(app, /Validate one buyer first/, 'Deals empty state must present one calm next action.');
assert.doesNotMatch(app, /No parcels match this filter\./, 'Deals empty state must not use dramatic filter-failure language.');
assert.doesNotMatch(app, /<div class="empty-state-icon">\$\{solidIndustryIcon\('empty'\)\}<\/div><span class="eyebrow">Nothing actionable in this view/, 'Deals empty state must not render the old oversized icon box.');
assert.match(app, /function renderLandControls/, 'Land page must expose dedicated state and sort controls.');
assert.match(app, /data-land-state/, 'Land page must let users focus listings by state.');
assert.match(app, /data-land-sort/, 'Land page must let users sort listings by market, state, enrichment, and builder fit.');
assert.match(app, /target\.hidden = true/, 'Legacy stage filters must be retired to remove overlapping controls from the Land page.');
assert.doesNotMatch(app, /\['seller-calls', 'Seller calls'\]/, 'Land page must not preserve old deal-stage filter clutter.');
assert.match(app, /landStateToggleOrder = \['FL', 'AZ', 'HI', 'NV', 'CA', 'TN', 'NC', 'TX', 'GA', 'SC', 'OH', 'ID', 'IN', 'PA'\]/, 'Land state toggle must include abbreviation-only queued states including OH/ID/IN/PA.');
assert.match(app, /const label = state === 'all' \? 'All' : state;/, 'Land state toggle should label all-states as All and state filters as abbreviations.');
assert.match(app, /const stateLabel = 'All';/, 'Land market toggle should label the aggregate market filter as All.');
assert.match(app, /function describeLandStateRecordScope/, 'Land state counts must explain whether records are broad state coverage or one populated seller lane.');
assert.match(app, /function actualLandRecordMarkets/, 'Land state counts must derive populated seller lanes from actual seller records, including virtual lanes like Dallas.');
assert.match(app, /function actualLandRecordMatchesMarket/, 'Land market lane counts must use exact seller market identity instead of loose text matching.');
assert.match(app, /const dealCount = landRecordCountForMarket\(allDeals, market\)/, 'Market lane counts must not leak Dallas/TX records into Austin or other text-matched lanes.');
assert.match(app, /actualLandRecordMatchesMarket\(parcel, activeMarket\)/, 'Selected market filtering must use exact seller market identity.');
assert.match(app, /land-state-index-card/, 'Land default market index must render state cards first, not expose every submarket lane.');
assert.match(app, /Parcels, proof, and owner motion stay hidden until a real market lane is chosen/, 'Land default route must hide parcel/proof/owner motion until market selection.');
assert.doesNotMatch(app, /<em>\$\{h\(activeState\.dealCount\)\} records · \$\{h\(activeState\.countyCount \|\| 0\)\} market lanes<\/em>/, 'Operating-state kicker must not return above Land market content.');
assert.doesNotMatch(app, /All markets/, 'Land UI should no longer say All markets.');
assert.doesNotMatch(app, /const label = state === 'all' \? 'All states' : state;/, 'Land state toggle should not use the longer All states label.');
assert.match(app, /function renderDealsMarketCoverage/, 'Deals page must render a market coverage shelf before seller deals exist.');
assert.match(app, /data-deals-market-key/, 'Deals page must let the operator switch market lanes independently from stage filters.');
assert.match(app, /<div role="button" tabindex="0" class="deals-market-card/, 'Deals market cards must avoid global button gradients while staying keyboard reachable.');
assert.doesNotMatch(app, /<button[^>]+class="deals-market-card/, 'Deals market cards must not use button elements that inherit global dark gradients.');
assert.match(app, /builderMarketSwitchboardEntries\(\)/, 'Deals page must reuse the shared market registry instead of hiding new markets.');
assert.match(app, /function renderSellerCallReference/, 'Deals execution conveyor must store the seller call reference in the webapp, not only in agent memory.');
assert.match(app, /Hi, this is Okeito\. I’m calling about your lot at \[property address\]/, 'Seller phone script opener must be available in the webapp reference section.');
assert.match(app, /subagents should reference it, not perform outreach/, 'Webapp seller script must preserve the subagent boundary: reference only, no outreach.');
assert.match(app, /const expansionStateCodes = new Set\(\['FL', 'AZ', 'HI', 'NV', 'CA', 'OH', 'ID', 'IN', 'PA', 'GA', 'SC'\]\)/, 'Deals page must pin newly added OH/ID/IN/PA plus GA/SC expansion markets near the top of the coverage shelf.');
assert.match(app, /\.\.\.expansionEntries, \.\.\.otherEntries/, 'Deals market coverage must surface expansion markets before older lanes.');
for (const key of ['port-charlotte-fl-33948', 'punta-gorda-fl-33983', 'port-charlotte-fl-33953', 'mohave-valley-az-86440', 'maricopa-ak-chin-az-85139', 'pahoa-keaau-hi', 'pahrump-nv-89048', 'joshua-tree-ca-92252', 'columbus-oh', 'boise-id', 'indianapolis-in', 'pittsburgh-pa', 'forsyth-ga', 'hall-ga', 'jackson-ga', 'douglas-ga', 'dorchester-sc', 'berkeley-sc', 'greenville-sc']) {
  assert.match(app, new RegExp(`key: '${key}'`), `Deals market coverage must include ${key} through the shared registry.`);
}
assert.match(app, /this market is visible, but no public seller record currently clears buyer demand/i, 'Deals empty copy must explain visible zero-deal markets.');
assert.match(app, /Attach public proof before contact or money review\./, 'Land primary instruction must expose the proof-first operator action before money review.');
assert.match(app, /function parcelListingState/, 'Deals must classify listing state instead of hiding records.');
assert.match(app, /if \(cachedScoredParcels\) return cachedScoredParcels;/, 'Land performance must cache expensive scored parcel generation across render cycles.');
assert.match(app, /if \(activeView === 'deals'\) \{[\s\S]{0,120}renderParcels\(\);[\s\S]{0,80}renderAppShell\(\);[\s\S]{0,40}return;/, 'Deals page load must render only the active Land panel instead of every hidden workspace panel.');
assert.match(app, /if \(cachedDealsMarketEntries\?\.key === cacheKey\) return cachedDealsMarketEntries\.entries;/, 'Deals market lane entries must be cached per state/market selection.');
assert.match(app, /if \(activeView !== 'deals'\) \{[\s\S]{0,120}renderBuilderListEnginePanel\(\)/, 'Land row selection must not rerender unrelated builder/closing panels on every parcel click.');
assert.match(app, /const selected = selectedParcelId \? getSelectedParcel\(visible\) : null;/, 'Land state and market switching must not auto-open the heavy selected parcel sheet.');
assert.match(app, /phase210-lightweight-selection/, 'Land performance pass must render a lightweight queue-first selection prompt before parcel detail.');
assert.match(css, /--land-final-css: consolidated-land-styles-no-stale-phase-overrides/, 'Land CSS must use the consolidated final stylesheet marker.');
assert.match(css, /body\[data-active-view="deals"\] #parcels \.land-listing-row \{[\s\S]{0,80}contain:layout paint style !important;/, 'Land queue rows must isolate layout and paint work.');
assert.match(css, /v1\.65 - Phase 38 Deals calm empty state/, 'Phase 38 route-scoped CSS marker missing.');
assert.match(css, /--phase38-deals-empty: compact-intentional-not-broken/, 'Deals route marker must document the intended state.');
assert.match(css, /#parcel-filters\.phase38-deals-segmented/, 'Deals filters must be styled as a segmented control.');
assert.match(css, /\.phase38-deals-empty[\s\S]*width: min\(100%, 640px\)/, 'Deals empty state must be compact, not full-width dramatic.');
assert.match(css, /\.phase38-deals-empty \.empty-state-icon[\s\S]*display: none !important/, 'Oversized empty-state icon box must stay hidden on Deals.');
assert.match(css, /body\[data-active-view="deals"\] footer[\s\S]*padding-bottom: 18px/, 'Deals footer/dead space must be pulled out of the visual field.');
assert.match(css, /v1\.73 - Deals market coverage: every builder market remains visible before seller deals exist/, 'Deals market coverage CSS marker missing.');
assert.match(css, /\.deals-market-grid[\s\S]{0,220}repeat\(auto-fit, minmax\(222px, 1fr\)\)/, 'Deals market coverage must scale to many markets.');
assert.match(css, /\.deals-market-card\.needs-work em[\s\S]{0,80}#8a5a13/, 'Deals low/no-data markets must have visible needs-work styling.');
assert.match(css, /v1\.74 - Deals market cards must beat global button gradients/, 'Deals market cards need a late contrast override against global button gradients.');
assert.match(css, /button\.deals-market-card\.deals-market-card[\s\S]{0,180}background-image: none !important/, 'Deals market card buttons must suppress inherited gradient backgrounds.');

assert.match(css, /v1\.97 - LandFlip seller-call reference lives in webapp, not the agent skill/, 'Seller-call reference CSS marker must document the webapp-owned script boundary.');
assert.match(css, /\.execution-call-reference[\s\S]{0,160}display: grid/, 'Seller-call reference must render as a compact operator reference card.');
assert.match(css, /\.seller-script-grid[\s\S]{0,120}repeat\(3, minmax\(0, 1fr\)\)/, 'Seller script capture checklist must be scannable on desktop.');
assert.match(css, /v1\.95 - Deals land listings are always visible; enrichment\/builder fit creates hierarchy, not hiding/, 'Phase 95 always-visible land ledger CSS marker missing.');
assert.match(css, /--phase95-deals-rule: always-visible-land-ledger-enrichment-builder-fit-hierarchy/, 'Deals CSS must encode the always-visible listing rule.');
assert.match(css, /\.land-listing-row\.listing-matched-enriched::before[\s\S]{0,160}var\(--deals-gold\)/, 'Matched and enriched land rows need a restrained gold priority rail.');
assert.match(css, /\.land-ledger-queue[\s\S]{0,180}background: transparent !important/, 'Land ledger must be an open surface, not another boxed panel.');
assert.match(css, /--land-final-css: consolidated-land-styles-no-stale-phase-overrides/, 'Land CSS must encode the final consolidated stylesheet rule.');
assert.match(css, /--land-brand-primary: #0b5a43/, 'Land palette must define a forest primary accent.');
assert.match(css, /--land-brand-gold: #a97622/, 'Land palette must reserve gold for metrics and value emphasis.');
assert.doesNotMatch(css, /--land-phase20[0-9]/, 'Stale Land phase custom-property markers must be removed from the final stylesheet.');
assert.doesNotMatch(css, /\/\* v2\.0[0-9]/, 'Stale Land phase comment blocks must be removed from the final stylesheet.');
assert.match(app, /function landParcelMissionTelemetry/, 'Phase 258 must derive parcel-level mission telemetry.');
assert.match(app, /phase258-mission-row/, 'Phase 258 must turn parcel rows into mission-control scan rows.');
assert.match(app, /phase258-readiness-stack/, 'Phase 258 must render proof/buildability/contact/buyer/money readiness stacks.');
assert.match(app, /phase258-selected-mission-sheet/, 'Phase 258 must render a selected parcel mission sheet.');
assert.match(app, /Lane mission control/, 'Phase 258 must make zero-count lanes explain the buyer-first sourcing gate.');
assert.match(app, /do not send anything automatically/, 'Phase 258 must preserve copy-paste/manual action safety.');
assert.match(css, /--phase258-parcel-mission-control: readiness-stack-next-action-selected-mission-sheet/, 'CSS must encode the Phase 258 parcel mission-control rule.');
assert.match(css, /--phase258-empty-lane-state: buyer-proof-before-owner-sourcing/, 'CSS must encode the Phase 258 empty lane buyer-proof rule.');
assert.match(app, /function renderLandMarketIndex/, 'Land default route must render a clear state-gated market index instead of the old state workbench.');
assert.match(app, /phase254-land-market-index/, 'Land market index must be a first-class render surface.');
assert.match(app, /phase255-land-state-index/, 'Land default selector must show states first before submarket lanes.');
assert.match(app, /phase255-land-submarket-index/, 'Land state routes must reveal submarket lanes only after a state is selected.');
assert.match(app, /phase256-land-state-detail-summary/, 'Selected state route must show a state summary before submarket lane cards.');
assert.match(app, /phase257-state-telemetry/, 'Selected state route must rank lanes as a telemetry command surface.');
assert.match(app, /phase257-ranked-lane/, 'State lane cards must carry ranked lane telemetry.');
assert.match(app, /Start here/, 'Selected state route must identify the recommended lane.');
assert.match(app, /Telemetry score/, 'Selected market brief must expose lane score as operator telemetry.');
assert.match(app, /phase257-market-operating-brief/, 'Selected market route must render a market operating brief.');
assert.match(app, /Seller outreach block/, 'Selected market brief must state why seller outreach is blocked or allowed.');
assert.match(app, /Quiet lanes/, 'Selected state route must distinguish populated lanes from quiet zero-count lanes.');
assert.match(app, /seller queue opens only after market selection/, 'Selected state route must keep seller queues closed until a submarket lane is chosen.');
assert.match(app, /const texasLandReports = \[/, 'TX Land section must store report metadata in the project.');
assert.match(app, /Dallas JV infill land \/ teardown seller report/, 'TX Land reports must include the Dallas JV seller research report.');
assert.match(app, /function renderTexasLandReports/, 'TX state route must render the Texas report dock.');
assert.match(app, /phase261-land-report-dock/, 'TX reports must have a dedicated report button/panel surface.');
assert.match(app, /Download full markdown/, 'TX report panel must expose the full markdown report file.');
assert.match(css, /--phase261-tx-reports: dallas-jv-infill-seller-intelligence/, 'TX report CSS must encode the Dallas JV report surface.');
assert.match(css, /\.land-report-card summary[\s\S]{0,240}cursor: pointer !important/, 'TX report card must behave like a reports button.');
assert.match(app, /phase254-land-selected-workspace/, 'Selected Land market must render a dedicated workspace shell.');
assert.match(css, /--phase254-land-ia-reset: market-index-first-selected-workspace-second/, 'Land CSS must encode the Phase 254 IA reset.');
assert.match(css, /--phase254-land-selected-workspace: market-menu-before-selected-content-no-state-workbench/, 'Selected Land market must keep the market menu before selected content without the state workbench.');
assert.match(css, /--phase255-land-selector: states-first-submarket-lanes-after-state/, 'Land CSS must encode the state-first selector rule.');
assert.match(css, /--phase257-spacex-land-command: ranked-lane-telemetry-operating-briefs/, 'Land CSS must encode the Phase 257 SpaceX telemetry command surface.');
assert.match(css, /--phase257-market-operating-brief: spacex-telemetry-decision-ledger/, 'Selected market CSS must encode the Phase 257 operating brief design.');
assert.match(app, /phase256-land-market-breadcrumb/, 'Selected market view must show a Land/state/market breadcrumb.');
assert.match(css, /phase256-land-state-detail-summary[\s\S]{0,220}grid-area: summary/, 'Selected state summary must occupy its own grid row before submarket lanes.');
assert.match(css, /grid-template-areas: "hero" "filter" "summary" "grid"/, 'Mobile Land state route must keep the summary between filter and lane grid.');
assert.match(app, /land-selected-state-switcher/, 'Selected Land market view must provide a state switcher so operators can change states without returning to the root.');
assert.match(app, /land-back-to-state-index/, 'Selected Land market view must provide an obvious back affordance to the main state index.');
assert.match(app, /data-land-market-state/, 'Land market cards must carry state so selecting a market swaps the state-scoped content underneath.');
assert.match(app, /function landMarketRouteHash/, 'Land market selections must be route-addressable like Builders market selections.');
assert.match(app, /#deals\/market\//, 'Land market route should support direct market URLs.');
assert.doesNotMatch(app, /State → lane → parcel\./, 'Land default IA must no longer force state-first lane-first navigation.');
assert.doesNotMatch(app, /Land · state workbench/, 'Land default IA must not surface the old state workbench headline.');
assert.doesNotMatch(app, /phase211-one-state-switcher/, 'Land page must remove the old always-present state switcher surface.');
assert.doesNotMatch(app, /state-first-workbench state-data-workbench land-state-data-workbench/, 'Land page must remove the old state-first workbench wrapper.');
assert.doesNotMatch(app, /is-state-required/, 'Land market lanes must not hide behind a state-required dead-end.');
assert.match(css, /\.deal-workbench:not\(\.phase210-lightweight-selection\) > \.deal-action[\s\S]{0,80}display: none !important/, 'Selected parcel view must remove the duplicate lower action rail.');
assert.match(css, /\.phase215-queue-rail[\s\S]{0,260}border-right: 1px solid var\(--land-award-line\)/, 'Land queue must be a quiet rail, not a boxed panel.');
assert.match(css, /\.deals-primary-action[\s\S]{0,320}grid-column:1\/-1 !important/, 'Selected-state workbench should start with one full-width next-action instruction row.');
assert.match(css, /\.land-listing-row\.phase209-scan-rail-row[\s\S]{0,520}grid-template-areas/, 'Queue rows must use a compact Apple-sidebar grid.');
assert.match(css, /\.land-row-signals\.phase209-proof-contact-fit :where\(\.risk-good,\.risk-neutral,\.risk-warn,\.dallas-proof-row-chip,\.dallas-sprint-chip\) \{ display:none !important; \}/, 'Queue must hide low-signal clean/repeated badges.');
assert.match(css, /\.land-listing-row\.phase209-scan-rail-row\.active \.land-row-signals\.phase209-proof-contact-fit \.dallas-sprint-chip \{ display:inline-flex !important; \}/, 'Dallas sprint chip may appear only on the active queue row.');
assert.match(css, /\.land-calm-operator-sheet\.phase208-calm-operator-sheet/, 'Selected parcel must still style as a calm operator sheet.');
assert.match(app, /land-proof-action-gates phase212-progressive-detail/, 'Selected parcel detail must start with proof/action/contact/buyer/money gate summary.');
assert.match(app, /const ACTIVITY_CHANNELS = \['phone', 'email', 'mail'\]/, 'Land rows must share call/email/mail activity channels.');
assert.match(app, /data-toggle-\$\{h\(scope\)\}-activity/, 'Land rows must render per-item activity toggle controls.');
assert.match(app, /setActivityChannel\('land', parcelKey, channel/, 'Land activity toggles must persist into browser-local workspace activity state.');
assert.match(app, /class="land-row-select" data-select-parcel/, 'Land row selection must stay separate from activity buttons to avoid nested-button toggles.');
assert.match(app, /renderBuyerSendMemoCard\(buyerMemo, \{ compact: true, open: false \}\)/, 'Buyer memo must be quiet disclosure by default in the selected sheet.');
assert.match(app, /renderOperatorChecklist\(operatorChecklist, \{ compact: true, open: false \}\)/, 'Call-to-close timeline must be collapsed until needed.');
assert.match(css, /--land-phase212-selected-detail: proof-action-contact-buyer-money-disclosure/, 'Selected detail CSS must encode the progressive-disclosure hierarchy.');
assert.match(css, /\.phase212-proof-depth:not\(\[open\]\)[\s\S]{0,160}\*\:not\(summary\)/, 'Dallas proof sprint depth must stay behind a quiet disclosure by default.');
assert.match(css, /\.land-money-sheet\.phase208-money-last:not\(\[open\]\) :where\(\.deal-strip,\.phase-one-detail-grid\) \{ display:none !important; \}/, 'Money metrics must remain hidden until the gated money sheet is opened.');
assert.match(css, /\.land-raw-depth[\s\S]{0,140}border:1px solid rgba\(11,90,67,\.13\)/, 'Raw owner/source depth must remain a gated lower disclosure.');
assert.match(css, /\.land-agent-intake-gate,[\s\S]{0,160}\.land-recon-import-path[\s\S]{0,160}grid-template-columns:minmax\(240px,\.34fr\) minmax\(0,1fr\)/, 'Proof/import surfaces must stay open two-column ledgers on desktop.');
assert.match(css, /\.land-agent-ledger li[\s\S]{0,180}grid-template-columns:minmax\(100px,\.22fr\) minmax\(80px,\.16fr\) minmax\(0,1fr\)/, 'Land agent contract rows must read as a calm ledger.');
assert.match(css, /#parcel-filters\.land-stage-filters-retired \{ display:none !important;/, 'Retired Land filter speck must stay hidden after consolidation.');
assert.match(css, /@media \(max-width:760px\)[\s\S]{0,520}\.nav \.app-tabs[\s\S]{0,180}grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/, 'Mobile nav tabs must wrap into a visible grid, not clip horizontally.');
assert.match(css, /body\[data-active-view="deals"\] #parcels \.phase208-selected-parcel-summary \{ position:static !important;/, 'Mobile selected summary must not stick over the operator sheet.');
assert.match(css, /--land-phase228-empty-inspector-width: match-selected-detail-workbench/, 'Land empty inspector must encode the selected-detail width rule.');
assert.match(css, /\.deal-workbench\.phase210-lightweight-selection[\s\S]{0,180}grid-template-columns: minmax\(340px, 410px\) minmax\(0, 1fr\) !important/, 'Land empty inspector workbench must use the same queue/detail columns as the selected parcel layout.');
assert.match(css, /\.phase210-lightweight-selection > \.phase210-select-parcel-prompt[\s\S]{0,120}grid-column: 2 !important;[\s\S]{0,80}width: 100% !important/, 'Land empty inspector must fill the detail column instead of shrinking to a narrow island.');
assert.match(css, /--land-phase219-desktop-width: open-surface-flattened-state-workbench-full-bleed/, 'Land desktop pass must encode the full-width flattened work surface rule.');
assert.match(css, /phase218-builder-style-workbench > \.state-data-workbench,[\s\S]{0,140}display: contents !important/, 'Land desktop state workbench must flatten nested wrapper gutters.');
assert.match(css, /phase218-builder-style-workbench\.builders-phase83-workbench[\s\S]{0,360}grid-template-columns: minmax\(170px, \.22fr\) minmax\(450px, \.47fr\) minmax\(300px, \.31fr\) !important/, 'Land desktop top workbench must use three real columns instead of a shrunken nested island.');
assert.match(css, /deal-workbench\.phase210-lightweight-selection,[\s\S]{0,220}grid-template-columns: minmax\(390px, \.39fr\) minmax\(0, \.61fr\) !important/, 'Land desktop queue/detail workbench must use the full holder width.');
assert.match(html, /src\/styles\.css\?v=phase244/, 'Index must bust CSS cache through the latest Today hierarchy/Land Offer Math/SMS draft review pass while preserving empty inspector parity.');
assert.match(app, /let freeGovOwnerSources = null;/, 'App must store the free-government owner source matrix.');
assert.match(app, /loadFreeGovOwnerSources\(\)\.then\(renderAll\)/, 'App must load the free-government owner source matrix into the UI.');
assert.match(app, /function renderFreeGovOwnerSourceBoard/, 'Sources page must render stored market owner-source agent lanes.');
assert.match(app, /function deriveLandLotEnrichment/, 'Land page must derive per-lot enrichment from app-loaded parcel data.');
assert.match(app, /_landLotEnrichment: landLotEnrichment/, 'Visible Land rows must carry derived enrichment on the app-loaded row object.');
assert.match(app, /function landLotFactChips/, 'Land page must render compact and selected enriched lot facts.');
assert.match(app, /landLotFactChips\(parcel, \{ compact: true \}\)/, 'Land queue rows must surface compact enriched lot facts.');
assert.match(app, /landLotFactChips\(selected\)/, 'Selected parcel detail must surface enriched lot facts above raw depth.');
assert.match(app, /Skip-trace locked/, 'Land lot enrichment must keep no-contact rows locked instead of fabricating contacts.');
assert.match(app, /Human-review owner before contact work\./, 'Land lot enrichment must route entity\/estate\/multi-owner rows to human review.');
assert.match(app, /Every market is stored\. Real land-lot markets get execution agents\./, 'Sources UI must explain stored zero markets and active land-lot agents.');
assert.match(app, /Zero-count markets remain ready/, 'Sources UI must preserve zero-count markets as ready lanes.');
assert.match(app, /Fabricated contacts/, 'Sources UI must expose zero-fabrication contact accounting.');
assert.match(css, /--land-phase229-free-gov-owner-agents: stored-zero-count-markets-active-owner-anchor-agents/, 'CSS must encode the free-gov owner-source agent pass.');
assert.match(css, /--land-phase230-lot-enrichment: app-loaded-apn-owner-contact-utility-facts/, 'CSS must encode app-loaded per-lot enrichment facts.');
assert.match(css, /--land-phase231-empty-detail-parity: empty-inspector-reserves-selected-sheet-geometry/, 'Land empty inspector must encode the selected-detail geometry parity pass.');
assert.match(app, /phase231-empty-action-row/, 'Unselected Land queue must keep the same full-width next-action row as selected detail.');
assert.match(app, /deal-detail land-empty-inspector/, 'Unselected Land inspector must reuse selected detail sheet geometry classes.');
assert.match(css, /\.phase210-lightweight-selection > \.phase231-empty-detail-parity,[\s\S]{0,420}max-width: none !important;[\s\S]{0,260}border-left: 1px solid/, 'Unselected Land inspector must fill the selected detail column and keep the same sheet edge.');
assert.match(css, /\.land-row-lot-facts/, 'Land row lot facts need route-scoped styling.');
assert.match(css, /\.land-selected-lot-facts[\s\S]{0,220}grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/, 'Selected detail lot facts must render as a quiet two-column ledger.');
assert.match(css, /grid-template-areas: "idx title" "idx meta" "idx facts" "idx reason" "idx badges" "idx activity"/, 'Land row grid must reserve a stable facts row.');
assert.ok(readFileSync('data/generated/free_gov_owner_sources.json', 'utf8').includes('"contactsFabricated": 0'), 'Free-gov owner source matrix must preserve zero-fabrication accounting.');

console.log('deals empty/filter UI tests passed');
