import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const app = readFileSync('src/app.mjs', 'utf8');
const css = readFileSync('src/styles.css', 'utf8');

assert.match(app, /phase38-deals-empty/, 'Deals empty state must use the Phase 38 compact component.');
assert.match(app, /This lane is intentionally quiet\./, 'Deals empty state must explain intentional emptiness quickly.');
assert.match(app, /Why empty:/, 'Deals empty state must include a small why-empty explanation.');
assert.match(app, /Validate one buyer first/, 'Deals empty state must present one calm next action.');
assert.doesNotMatch(app, /No parcels match this filter\./, 'Deals empty state must not use dramatic filter-failure language.');
assert.doesNotMatch(app, /<div class="empty-state-icon">\$\{solidIndustryIcon\('empty'\)\}<\/div><span class="eyebrow">Nothing actionable in this view/, 'Deals empty state must not render the old oversized icon box.');
assert.match(app, /function renderLandControls/, 'Land page must expose dedicated state and sort controls.');
assert.match(app, /data-land-state/, 'Land page must let users focus listings by state.');
assert.match(app, /data-land-sort/, 'Land page must let users sort listings by market, state, enrichment, and builder fit.');
assert.match(app, /target\.hidden = true/, 'Legacy stage filters must be retired to remove overlapping controls from the Land page.');
assert.doesNotMatch(app, /\['seller-calls', 'Seller calls'\]/, 'Land page must not preserve old deal-stage filter clutter.');
assert.match(app, /function renderDealsMarketCoverage/, 'Deals page must render a market coverage shelf before seller deals exist.');
assert.match(app, /data-deals-market-key/, 'Deals page must let the operator switch market lanes independently from stage filters.');
assert.match(app, /<div role="button" tabindex="0" class="deals-market-card/, 'Deals market cards must avoid global button gradients while staying keyboard reachable.');
assert.doesNotMatch(app, /<button[^>]+class="deals-market-card/, 'Deals market cards must not use button elements that inherit global dark gradients.');
assert.match(app, /builderMarketSwitchboardEntries\(\)/, 'Deals page must reuse the shared market registry instead of hiding new markets.');
assert.match(app, /function renderSellerCallReference/, 'Deals execution conveyor must store the seller call reference in the webapp, not only in agent memory.');
assert.match(app, /Hi, this is Okeito\. I’m calling about your lot at \[property address\]/, 'Seller phone script opener must be available in the webapp reference section.');
assert.match(app, /subagents should reference it, not perform outreach/, 'Webapp seller script must preserve the subagent boundary: reference only, no outreach.');
assert.match(app, /const expansionStateCodes = new Set\(\['GA', 'SC'\]\)/, 'Deals page must pin new GA/SC expansion markets near the top of the coverage shelf.');
assert.match(app, /\.\.\.expansionEntries, \.\.\.otherEntries/, 'Deals market coverage must surface expansion markets before older lanes.');
for (const key of ['forsyth-ga', 'hall-ga', 'jackson-ga', 'douglas-ga', 'dorchester-sc', 'berkeley-sc', 'greenville-sc']) {
  assert.match(app, new RegExp(`key: '${key}'`), `Deals market coverage must include ${key} through the shared registry.`);
}
assert.match(app, /this market is visible, but no public seller record currently clears buyer demand/, 'Deals empty copy must explain visible zero-deal markets.');
assert.match(app, /Enrich one owner contact, then verify gently before any sales pitch\./, 'Land primary instruction must expose one clear safe next action.');
assert.match(app, /function parcelListingState/, 'Deals must classify listing state instead of hiding records.');
assert.match(app, /return scoredParcels\(\)\.map\(parcel => \(\{/, 'Deals visible parcels must keep all source-backed records visible.');
assert.match(app, /selectedStateMatch: selectedLandStateFilter === 'all' \|\| rowState\(parcel\) === selectedLandStateFilter/, 'Land state focus must compute state match for IA scent.');
assert.match(app, /if \(selectedLandStateFilter !== 'all' && !parcel\.selectedStateMatch\) return false;/, 'Land state selector must own the list instead of leaving a confusing all-state smorgasbord.');
assert.match(app, /selectedMarket\?\.isDallasProofLane \? Boolean\(dallasProofRowForParcel\(parcel\)\)/, 'Dallas proof lane must filter listings to Dallas proof sprint rows only.');
assert.match(app, /selectedLandStateFilter === 'TX' && selectedDealsMarketKey === 'dallas-tx'/, 'Dallas proof sprint surface must render only inside TX → Dallas lane.');
assert.match(app, /class="land-state-workbench-brief phase206-land-state-workbench"/, 'Selected Land state must render a Phase 206 operating brief before the workbench.');
assert.match(app, /Work one clean next action\./, 'Selected-state brief must make the next action the scan anchor.');
assert.match(app, /class="deal-workbench phase206-selected-state-workbench"/, 'Selected-state Land workbench must declare the Phase 206 workbench hierarchy.');
assert.match(app, /class="land-raw-depth"/, 'Owner/source/intake depth must move behind a raw-depth disclosure.');
assert.match(app, /Open only when editing evidence/, 'Raw CRM/source depth must be demoted below the action path.');
assert.match(app, /class="land-command-surface phase202-land-state-first phase207-top-control-cohesion/, 'Land command surface must declare the state-first IA and top-control cohesion pass.');
assert.match(app, /phase207-state-gate-handoff/, 'All-states Land command must hand off state choice to the state ledger instead of rendering a duplicate state selector.');
assert.match(app, /The state gate below is the selector in All-states view\./, 'All-states copy must explain why the lower state ledger is the selector.');
assert.match(app, /State switcher/, 'Selected-state mode may keep a compact state switcher after the primary state has been chosen.');
assert.match(app, /Choose state\. Then lane\. Then parcel\./, 'Land page copy must make the state-led operating model explicit.');
assert.match(app, /Choose a state above to reveal its market lanes/, 'All-states mode must prompt for state first instead of showing every market lane.');
assert.match(app, /function renderLandStateDecisionBoard/, 'All-states mode must render a state decision board before opening parcel detail.');
assert.match(app, /class="land-state-decision-board phase203-land-state-gate"/, 'State decision board must declare the Phase 203 state-gate pass.');
assert.match(app, /if \(selectedLandStateFilter === 'all'\) \{[\s\S]{0,180}renderLandStateDecisionBoard\(\)/, 'All-states mode must stop at the state gate instead of rendering the parcel cockpit.');
assert.match(app, /if \(selectedLandStateFilter === 'all'\) selectedDealsMarketKey = 'all';/, 'Returning to all states must clear subordinate market lane filters.');
assert.match(app, /function landSortValue/, 'Land listings need a sortable value model for priority, state, market, enrichment, and builder fit.');
assert.doesNotMatch(app, /if \(filter === 'seller-calls'\) return parcel\.action/, 'Deals stage filters must not hide land listings anymore.');
assert.match(app, /listing-\$\{h\(listingState\.stage\)\}/, 'Land rows must expose visual state classes for enrichment/builder fit.');
assert.match(app, /Matched \+ enriched/, 'Land rows must distinguish records that are both contact-enriched and builder-matched.');
assert.match(app, /land-listing-status-strip/, 'Selected detail must show contact/builder-fit/priority progression.');
assert.match(app, /function renderLandAgentIntakeGate/, 'Land page must expose a subagent intake proof gate.');
assert.match(app, /Proof rules/, 'Land page must label the agent intake proof gate clearly.');
assert.match(app, /Rows stay available for research, but seller motion only starts after public proof/, 'Land page must explain the visible subagent append boundary without promoting calls.');
assert.match(app, /subagents reference the webapp script; they do not perform outreach/, 'Land agent intake gate must preserve the no-agent-outreach boundary.');
assert.match(app, /Public proof', 'Promotes'/, 'Agent intake contract must promote public proof without hiding raw findings.');
assert.match(app, /Owner contact', 'Quarantined'/, 'Agent intake contract must keep weak owner contact visible but not callable.');
assert.match(app, /Builder fit', 'Computed'/, 'Agent intake contract must compute builder fit from evidence rather than guessing.');
assert.match(app, /land-selected-summary/, 'Selected Land detail must expose a compact proof/contact/buyer/action summary.');
assert.match(app, /land-close-timeline/, 'Call-to-close control must render as a compact timeline instead of boxed steps.');
assert.match(app, /land-settings-sheet/, 'Buyer memo and feedback must sit inside one lower settings sheet.');
assert.match(app, /Record the answer that rewrites tomorrow’s calls/, 'Buyer feedback copy must be compressed into a calm settings-row prompt.');

assert.match(css, /v1\.65 - Phase 38 Deals calm empty state/, 'Phase 38 route-scoped CSS marker missing.');
assert.match(css, /--phase38-deals-empty: compact-intentional-not-broken/, 'Deals route marker must document the intended state.');
assert.match(css, /#parcel-filters\.phase38-deals-segmented/, 'Deals filters must be styled as a segmented control.');
assert.match(css, /\.phase38-deals-empty[\s\S]*width: min\(100%, 640px\)/, 'Deals empty state must be compact, not full-width dramatic.');
assert.match(css, /\.phase38-deals-empty \.empty-state-icon[\s\S]*display: none !important/, 'Oversized empty-state icon box must stay hidden on Deals.');
assert.match(css, /body\[data-active-view="deals"\] footer[\s\S]*padding-bottom: 18px/, 'Deals footer/dead space must be pulled out of the visual field.');
assert.match(css, /v1\.73 - Deals market coverage: every builder market remains visible before seller deals exist/, 'Deals market coverage CSS marker missing.');
assert.match(css, /\.deals-market-grid[\s\S]{0,220}repeat\(auto-fit, minmax\(222px, 1fr\)\)/, 'Deals market coverage must scale to many markets.');
assert.match(css, /\.deals-market-card\.needs-work em[\s\S]{0,80}#8a5a13/, 'Deals low/no-data markets must have visible needs-work styling.');
assert.match(css, /v1\.74 - Deals market cards must beat global button gradients/, 'Deals market cards need a late contrast override against global button gradients.');
assert.match(css, /button\.deals-market-card\.deals-market-card[\s\S]{0,180}background-image: none !important/, 'Deals market card buttons must suppress inherited gradient backgrounds.');

assert.match(css, /v1\.97 - LandFlip seller-call reference lives in webapp, not the agent skill/, 'Seller-call reference CSS marker must document the webapp-owned script boundary.');
assert.match(css, /\.execution-call-reference[\s\S]{0,160}display: grid/, 'Seller-call reference must render as a compact operator reference card.');
assert.match(css, /\.seller-script-grid[\s\S]{0,120}repeat\(3, minmax\(0, 1fr\)\)/, 'Seller script capture checklist must be scannable on desktop.');
assert.match(css, /v1\.95 - Deals land listings are always visible; enrichment\/builder fit creates hierarchy, not hiding/, 'Phase 95 always-visible land ledger CSS marker missing.');
assert.match(css, /--phase95-deals-rule: always-visible-land-ledger-enrichment-builder-fit-hierarchy/, 'Deals CSS must encode the always-visible listing rule.');
assert.match(css, /\.land-listing-row\.listing-matched-enriched::before[\s\S]{0,160}var\(--deals-gold\)/, 'Matched and enriched land rows need a restrained gold priority rail.');
assert.match(css, /\.land-ledger-queue[\s\S]{0,180}background: transparent !important/, 'Land ledger must be an open surface, not another boxed panel.');
assert.match(css, /v1\.98 - Land Markets page: dedicated plot browser, state\/market sorting, enrichment\/builder-match scent/, 'Phase 98 Land Markets page CSS marker missing.');
assert.match(css, /--phase98-land-rule: dedicated-land-markets-page-state-market-sort-enrichment-builder-match/, 'Land page must encode the dedicated market browser rule.');
assert.match(css, /--land-phase202-rule: state-first-lane-second-dallas-proof-scoped/, 'Phase 202 must encode state-first IA and scoped Dallas proof rule.');
assert.match(css, /\.land-command-surface\.phase202-land-state-first[\s\S]{0,260}grid-template-columns: minmax\(260px, \.52fr\) minmax\(0, 1\.18fr\)/, 'Phase 202 command surface must use calmer Apple-grade hierarchy proportions.');
assert.match(css, /\.land-market-lane-selector \.deals-market-card\.active[\s\S]{0,180}rgba\(11, 90, 67, \.055\)/, 'Phase 202 active market lane should be a quiet tint, not a loud slab.');
assert.match(css, /\.land-market-lane-selector \.deals-market-card kbd[\s\S]{0,120}var\(--land-gold\)/, 'Phase 202 market lane state chips should use restrained gold for key data.');
assert.match(css, /\.land-market-lane-selector\.is-state-required \.deals-market-grid[\s\S]{0,140}display: block !important/, 'All-states market area should be a quiet state-first prompt, not a full lane grid.');
assert.match(css, /--land-phase203-rule: all-states-state-gate-before-parcel-cockpit/, 'Phase 203 must encode all-states as a state gate before parcel detail.');
assert.match(css, /v2\.03b - Mobile nav stays visible while Land state gate owns the first screen/, 'Phase 203 mobile QA must keep primary nav visible instead of clipped.');
assert.match(css, /--land-phase204-rule: mobile-listing-buttons-use-block-flow-no-overlap/, 'Phase 204 must lock mobile listing buttons into block flow to avoid iOS Safari row overlap.');
assert.match(css, /--land-phase205-rule: apple-calm-state-led-scan-hierarchy-no-smorgasbord/, 'Phase 205 must encode the Land-only Apple calm scan hierarchy rule.');
assert.match(css, /--land-phase205b-correction: command-memo-scale-mobile-state-controls-readable/, 'Phase 205 self-review correction must reduce second-hero scale and fix mobile state controls.');
assert.match(css, /--land-phase205c-correction: compact-viewports-stack-command-controls/, 'Phase 205 compact viewport correction must prevent squeezed two-column Land controls.');
assert.match(css, /--land-phase205d-correction: compact-state-counts-stay-attached/, 'Phase 205 compact control correction must keep state labels and counts visually paired.');
assert.match(css, /--land-phase206-rule: selected-state-workbench-action-path-before-raw-depth/, 'Phase 206 must encode the selected-state action-path hierarchy.');
assert.match(css, /--land-phase206b-correction: selected-state-lane-browser-is-compact-control/, 'Phase 206 self-review must demote the selected-state lane browser into a compact control.');
assert.match(css, /--land-phase206c-correction: lane-browser-copy-horizontal-no-vertical-shards/, 'Phase 206 final self-review must prevent selected lane browser copy from collapsing vertically.');
assert.match(css, /--land-phase207-rule: one-all-states-selector-state-ledger-owns-choice/, 'Phase 207 must encode one All-states state selector with the state ledger owning choice.');
assert.match(css, /--land-phase207b-correction: tighter-command-to-state-gate-rhythm/, 'Phase 207 self-review must tighten command-to-state-gate rhythm after pixel review.');
assert.match(css, /--land-phase207c-correction: selected-lane-cards-wrap-inside-command-rail/, 'Phase 207 selected-state self-review must prevent lane cards from overflowing the command rail.');
assert.match(css, /\.land-state-orientation\.phase207-state-gate-handoff/, 'Phase 207 must replace the duplicate top All-states state selector with an orientation handoff.');
assert.match(css, /\.land-command-surface\.phase207-top-control-cohesion[\s\S]{0,260}min-height: 0 !important/, 'Phase 207 must remove irregular command-surface vertical padding/min-height.');
assert.match(css, /\.land-state-decision-board\.phase203-land-state-gate[\s\S]{0,260}margin-top: var\(--land-rhythm-lg\)/, 'Phase 207 must regularize spacing between command surface and state ledger.');
assert.match(css, /\.land-state-workbench-brief\.phase206-land-state-workbench/, 'Phase 206 must style the selected-state operating brief.');
assert.match(css, /\.land-raw-depth:not\(\[open\]\) \.detail-grid \{ display: none !important; \}/, 'Raw owner/source/intake detail must stay collapsed until explicitly opened.');
assert.match(css, /--land-brand-primary: #0b5a43/, 'Phase 205 Land palette must define a forest primary accent.');
assert.match(css, /--land-brand-gold: #a97622/, 'Phase 205 Land palette must reserve gold for metrics and value emphasis.');
assert.match(css, /\.land-market-lane-selector\.is-state-required \{[\s\S]{0,80}display: none !important/, 'All-states should remove the duplicate market-lane prompt and let the state decision ledger carry the job.');
assert.match(css, /\.deals-primary-action[\s\S]{0,320}grid-column: 1 \/ -1 !important/, 'Selected-state workbench should start with one full-width next-action instruction row.');
assert.match(css, /@media \(max-width: 760px\)[\s\S]{0,900}\.land-listing-row \{[\s\S]{0,260}display: block !important/, 'Mobile Land listing rows must not use CSS grid on button controls.');
assert.match(css, /\.land-listing-row b,[\s\S]{0,220}\.land-listing-row small,[\s\S]{0,220}\.land-listing-row em,[\s\S]{0,260}grid-area: auto !important/, 'Mobile Land row children must leave inherited grid areas and stack in normal flow.');
assert.match(css, /\.nav \.app-tabs[\s\S]{0,180}grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/, 'Mobile nav tabs must wrap into a visible grid, not clip horizontally.');
assert.match(css, /\.land-state-decision-board[\s\S]{0,220}grid-template-columns: minmax\(280px, \.52fr\) minmax\(0, 1fr\)/, 'State gate must read as an open decision ledger, not a boxed dashboard.');
assert.match(css, /\.land-state-decision-row\.recommended[\s\S]{0,180}inset 2px 0 0 var\(--land-forest/, 'Recommended state row should use a quiet rail rather than loud button chrome.');
assert.match(css, /\.land-command-surface[\s\S]{0,220}grid-template-columns: minmax\(280px, \.58fr\) minmax\(0, 1fr\)/, 'Land controls must be a calm command surface, not another boxed dashboard.');
assert.match(css, /\.land-state-filter\.active,[\s\S]{0,420}inset 2px 0 0 var\(--land-forest\)/, 'Active Land state/sort controls should use a quiet Apple rail.');
assert.match(css, /\.land-stage-filters-retired \{ display: none !important; \}/, 'Retired stage filters must stay visually removed.');
assert.match(css, /v1\.99 - Land agent intake gate: subagent rows must carry source\/contact\/builder-fit proof before promotion/, 'Phase 99 Land agent intake CSS marker missing.');
assert.match(css, /--phase99-land-agent-intake: zero-fabrication-subagent-proof-gate/, 'Land page must encode the zero-fabrication subagent proof gate.');
assert.match(css, /\.land-agent-intake-gate[\s\S]{0,220}grid-template-columns: minmax\(280px, \.52fr\) minmax\(0, 1fr\)/, 'Land agent intake gate must be an open two-column proof ledger on desktop.');
assert.match(css, /\.land-agent-ledger li[\s\S]{0,180}grid-template-columns: minmax\(100px, \.22fr\) minmax\(80px, \.16fr\) minmax\(0, 1fr\)/, 'Land agent contract rows must read as a calm ledger, not boxed cards.');
assert.match(css, /v1\.99b - Land controls must stay hairline rails, not dark button slabs/, 'Land controls need a late guard against dark button slabs.');
assert.match(css, /#parcels \.land-control-group button\.land-state-filter,[\s\S]{0,260}background-color: transparent !important/, 'Land state controls must stay transparent hairline rails.');
assert.match(css, /--land-phase201-rule: lower-depth-becomes-summary-timeline-settings-sheet/, 'Phase 201 lower-depth simplification marker missing.');
assert.match(css, /\.land-selected-summary[\s\S]{0,220}position: sticky !important/, 'Selected Land summary should stay available as the operator scans lower detail.');
assert.match(css, /\.land-close-timeline li[\s\S]{0,220}grid-template-columns/, 'Call-to-close timeline must be compact rows, not heavy cards.');
assert.match(css, /#parcel-filters\.land-stage-filters-retired[\s\S]{0,120}display: none !important/, 'Retired Land filter speck must stay hidden after pixel QA.');

console.log('deals empty/filter UI tests passed');
