import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

assert.match(css, /fonts\.googleapis\.com\/css2\?family=DM\+Mono[\s\S]*family=Space\+Grotesk/, 'Grotesk + DM Mono webfont import should lead the CSS');
assert.match(css, /v1\.44 - Phase 13 Apple-grade Grotesk\/DM Mono typography system/, 'Phase 13 global typography system marker required');
assert.match(css, /v1\.44\.1 - Phase 13 light-base typography bleed cleanup/, 'Phase 13 light-base cleanup should remove dark-mode bleed across routed pages');
assert.match(css, /v1\.44\.2 - Phase 13 nav typography specificity fix/, 'Phase 13 nav typography fix should prevent dark button leakage into tabs');
assert.match(css, /--font-grotesk: 'Space Grotesk', 'Grotesk'/, 'Grotesk token should use Space Grotesk with Grotesk fallback');
assert.match(css, /--font-mono: 'DM Mono'/, 'Mono token should use DM Mono');
assert.match(css, /family=Inter:wght@400;500;600;700;800/, 'Dense body typography should have a readable sans text engine');
assert.match(css, /body, button, input, textarea, select[\s\S]{0,110}font-family: var\(--font-grotesk\) !important/, 'Core UI controls should inherit the Grotesk system');
assert.match(css, /\.eyebrow,[\s\S]{0,460}font-family: var\(--font-mono\) !important/, 'Labels, badges, and microcopy should use DM Mono');
assert.match(css, /:is\(h1,h2,h3,h4\)[\s\S]{0,760}letter-spacing: -\.055em !important/, 'Headings should have unified tight Grotesk hierarchy');
assert.match(css, /--type-accent: #23d7c3/, 'Light-mode translation should retain the image-inspired cyan accent');
assert.match(css, /@media print[\s\S]{0,420}font-family: var\(--font-grotesk\) !important/, 'Print/PDF surfaces should be pulled into the same type system');
assert.match(css, /#operator-session-mode\.os8-session[\s\S]{0,520}linear-gradient\(135deg, rgba\(255,255,255,\.96\)/, 'Today operator session should be converted from dark panel to light base');
assert.match(css, /#sources-hub \.section-heading[\s\S]{0,420}linear-gradient\(135deg, rgba\(255,255,255,\.98\)/, 'Sources heading should use light base instead of legacy dark hero');
assert.match(css, /v1\.45 - Phase 14 unified light color, compact hierarchy, square buttons/, 'Phase 14 unified light color + square button pass required');
assert.match(css, /v1\.45\.1 - Phase 14 strict cleanup: Today graphic lightening, source color collapse, no rounded CTAs/, 'Strict follow-up cleanup should target Today, Sources, and residual rounded CTAs');
assert.match(css, /v1\.45\.2 - Phase 14 Today artifact final light-mode override/, 'Today artifact final override should remove dark graphic slab behavior');
assert.match(css, /v1\.45\.3 - Phase 14 body-active Today overrides beat legacy terrain CSS/, 'Today body-active legacy terrain CSS must be overridden');
assert.match(css, /v1\.46 - Phase 15 rectilinear Swiss Apple information hierarchy/, 'Phase 15 rectilinear hierarchy layer required');
assert.match(css, /v1\.46\.1 - Phase 15 high-specificity rectilinear cascade lock/, 'Phase 15 must beat older high-specificity rounded !important rules');
assert.match(html, /<main id="app">/, 'Phase 15 cascade lock requires main#app wrapper so high-specificity rectilinear rules apply');
assert.match(css, /--font-readable: 'Inter'/, 'Phase 15 should use a readable sans for dense paragraph sections');
assert.match(css, /\*,\n\*::before,\n\*::after \{\n  border-radius: 0 !important;/, 'Phase 15 should globally zero all visible corner radius');
assert.match(css, /--hierarchy-page-title: clamp\(36px, 5\.4vw, 72px\)/, 'Phase 15 hierarchy title scale token required');
assert.match(css, /--ui-accent: #13b9aa/, 'Unified palette should collapse accents to one restrained cyan signal');
assert.match(css, /\.wk-hero \{ min-height: clamp\(480px, 68vh, 660px\)/, 'Today hero should be compacted from billboard scale');
assert.match(css, /button, \.button-link,[\s\S]{0,520}border-radius: 0 !important/, 'Visible buttons and button-like CTAs must be square');
assert.match(css, /v1\.47 - Phase 16 cognitive-load kill pass: open ledgers, fewer boxes, sharper reading hierarchy/, 'Phase 16 cognitive-load kill pass marker required');
assert.match(css, /v1\.47\.1 - Phase 16 mobile deboxing correction/, 'Phase 16 should include mobile deboxing after screenshot QA');
assert.match(css, /v1\.47\.2 - Phase 16 no metric-box residue lock/, 'Phase 16 should remove residual metric-box styling after mobile QA');
assert.match(css, /v1\.48 - Phase 17 one-primary-action hierarchy with restrained SF-style line icons/, 'Phase 17 one-primary-action icon hierarchy marker required');
assert.match(css, /v1\.48\.1 - Phase 17 no-black-slab command correction/, 'Phase 17 should remove heavy black command slabs after screenshot QA');
assert.match(css, /v1\.48\.2 - Phase 17 no-black control slabs/, 'Phase 17 should remove remaining black control slabs after closing QA');
assert.match(css, /v1\.48\.3 - Phase 17 soften document step numerals/, 'Phase 17 should soften residual black document numerals after closing QA');
assert.match(css, /v1\.49 - Phase 17B Apple-industrial information hierarchy refinement/, 'Phase 17B refined hierarchy marker required');
assert.match(css, /v1\.49\.1 - Phase 17B closing de-nesting and proof-row quieting/, 'Phase 17B should include closing de-nesting after screenshot QA');
assert.match(css, /v1\.49\.2 - Phase 17B operational completion color system/, 'Phase 17B should restore at-a-glance done\/todo color states');
assert.match(css, /\.validation-queue-item\.is-emailed[\s\S]{0,260}border-left-color: var\(--done-accent\)/, 'Emailed builder rows need an immediate visual completion rail');
assert.match(css, /Apple review rule: one obvious action, then quiet evidence, then optional depth/, 'Phase 17B should encode the Apple review hierarchy rule');
assert.match(css, /#app \.primary-action-strip[\s\S]{0,520}grid-template-columns: minmax\(104px, \.26fr\) minmax\(0, 1fr\) auto !important/, 'Phase 17B should tighten the primary action strip into a calmer Swiss ledger');
assert.match(css, /\.product-icon[\s\S]{0,420}stroke-width: var\(--icon-stroke\)/, 'Phase 17 should use restrained stroke icons, not decorative icon boxes');
assert.match(css, /\.primary-action-strip[\s\S]{0,760}grid-template-columns: minmax\(140px, \.42fr\) minmax\(0, 1fr\) auto/, 'Phase 17 should introduce a consistent primary-action strip hierarchy');
assert.match(css, /Apple review rule: one obvious action, then evidence/, 'Phase 17 should de-emphasize secondary evidence after the primary action');
assert.match(css, /--font-heavy-text: 'Inter'/, 'Phase 16 should use Inter/SF-style sans for dense technology-app reading');
assert.match(css, /#app :where\(\.wk-workbench,[\s\S]{0,1400}border-top: 1px solid var\(--ledger-rule\) !important/, 'Phase 16 should replace nested modules with open ledger rules');
assert.match(css, /body\[data-active-view="today"\] #command \.wk-rail \{ display: none !important; \}/, 'Phase 16 should remove Today rail chrome from first-screen cognition');
assert.match(css, /#app \.app-panel\[hidden\]/, 'Phase 16 route isolation guard should remain after late layout overrides');
assert.match(html, /One seller\. One reason\. One next move\./, 'Deal page copy should be compressed into one-action hierarchy');
assert.match(html, /Buyer demand first\./, 'Builder page copy should make the hierarchy buyer-first');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /function productIcon\(kind\)[\s\S]{0,1400}class="product-icon"/, 'Phase 17 product icon helper should be present in app source');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /primary-action-strip builders-primary-action[\s\S]{0,220}Call the top permit-active builder/, 'Builders should expose one primary action before secondary evidence');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /is-emailed[\s\S]{0,160}needs-email/, 'Builder queue rows should add emailed/todo completion classes for visual scanning');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /data-email-state="\$\{outreach\.email \? 'done' : 'todo'\}"/, 'Builder queue rows should expose machine-readable email completion state');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /primary-action-strip closing-primary-action[\s\S]{0,260}Clear the title packet/, 'Closing should expose one primary action before secondary evidence');
assert.doesNotMatch(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /Phase 12 · Print detail finish/, 'Closing document packet should not expose implementation-phase residue');
const roundedButtonRules = [...css.matchAll(/([^{}]*button[^{}]*)\{([^{}]*border-radius[^{}]*)\}/g)]
  .filter(match => !/border-radius:\s*0\s*!important/.test(match[2]));
assert.deepEqual(roundedButtonRules.map(match => match[1].trim()).slice(0, 5), [], 'No button selector may retain rounded corner radius');

console.log('global typography tests passed');
