import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

assert.doesNotMatch(css, /fonts\.googleapis\.com|DM\+Mono|Space\+Grotesk|DM Mono|Space Grotesk/, 'Old external stylistic webfont imports must be removed');
assert.match(css, /v1\.44 - Phase 13 Apple-grade unified typography system/, 'Phase 13 global typography system marker required');
assert.match(css, /v1\.44\.1 - Phase 13 light-base typography bleed cleanup/, 'Phase 13 light-base cleanup should remove dark-mode bleed across routed pages');
assert.match(css, /v1\.44\.2 - Phase 13 nav typography specificity fix/, 'Phase 13 nav typography fix should prevent dark button leakage into tabs');
assert.match(css, /--font-grotesk: ui-sans-serif, -apple-system, BlinkMacSystemFont, "SF Pro Text", "Inter"/, 'Grotesk token should collapse into Apple/SF/Inter system typography');
assert.match(css, /--font-mono: ui-sans-serif, -apple-system, BlinkMacSystemFont, "SF Pro Text", "Inter"/, 'Old monospace label font should collapse into the same Apple system voice');
assert.doesNotMatch(css, /family=Inter:wght@400;500;600;700;800/, 'Dense body typography should not depend on external Inter webfont import');
assert.match(css, /body, button, input, textarea, select[\s\S]{0,110}font-family: var\(--font-grotesk\) !important/, 'Core UI controls should inherit the Grotesk system');
assert.match(css, /\.eyebrow,[\s\S]{0,460}font-family: var\(--font-grotesk\) !important/, 'Labels, badges, and microcopy should use the unified Apple system type voice');
assert.match(css, /:is\(h1,h2,h3,h4\)[\s\S]{0,760}letter-spacing: -\.055em !important/, 'Headings should have unified tight Grotesk hierarchy');
assert.match(css, /--type-accent: #23d7c3/, 'Light-mode translation should retain the image-inspired cyan accent');
assert.match(css, /@media print[\s\S]{0,420}font-family: var\(--font-grotesk\) !important/, 'Print/PDF surfaces should be pulled into the same type system');
assert.match(css, /#operator-session-mode\.os8-session[\s\S]{0,520}linear-gradient\(135deg, rgba\(255,255,255,\.96\)/, 'Today operator session should be converted from dark panel to light base');
assert.match(css, /#sources-hub \.section-heading[\s\S]{0,420}linear-gradient\(135deg, rgba\(255,255,255,\.98\)/, 'Sources heading should use light base instead of legacy dark hero');
assert.match(css, /v1\.45 - Phase 14 unified light color, compact hierarchy, square buttons/, 'Phase 14 unified light color + square button pass required');
assert.match(css, /v1\.45\.1 - Phase 14 strict cleanup: Today graphic lightening, source color collapse, no rounded CTAs/, 'Strict follow-up cleanup should target Today, Sources, and residual rounded CTAs');
assert.match(css, /v1\.45\.2 - Source row micro-fit: protect labels from count chrome/, 'Source row micro-fit marker should remain after token cleanup');
assert.match(css, /v1\.45\.3 - Phase 14 body-active Today overrides beat legacy field CSS/, 'Today body-active legacy field CSS must be overridden');
assert.match(css, /v1\.46 - Phase 15 rectilinear Swiss Apple information hierarchy/, 'Phase 15 rectilinear hierarchy layer required');
assert.match(css, /v1\.46\.1 - Phase 15 high-specificity rectilinear cascade lock/, 'Phase 15 must beat older high-specificity rounded !important rules');
assert.match(html, /<main id="app">/, 'Phase 15 cascade lock requires main#app wrapper so high-specificity rectilinear rules apply');
assert.match(css, /--font-readable: 'Inter'/, 'Phase 15 should use a readable sans for dense paragraph sections');
assert.match(css, /\*,\n\*::before,\n\*::after \{\n  border-radius: 0 !important;/, 'Phase 15 should globally zero all visible corner radius');
assert.match(css, /--hierarchy-page-title: clamp\(36px, 5\.4vw, 72px\)/, 'Phase 15 hierarchy title scale token required');
assert.match(css, /--ui-accent: #13b9aa/, 'Unified palette should collapse accents to one restrained cyan signal');
assert.match(css, /\.wk-hero \{ min-height: clamp\(480px, 68vh, 660px\)/, 'Today hero should be compacted from display scale');
assert.match(css, /button, \.button-link,[\s\S]{0,520}border-radius: 0 !important/, 'Visible buttons and button-like CTAs must be square');
assert.match(css, /v1\.47 - Phase 16 cognitive-load kill pass: open ledgers, fewer boxes, sharper reading hierarchy/, 'Phase 16 cognitive-load kill pass marker required');
assert.match(css, /v1\.47\.1 - Phase 16 mobile deboxing correction/, 'Phase 16 should include mobile deboxing after screenshot QA');
assert.match(css, /v1\.47\.2 - Phase 16 no metric-box residue lock/, 'Phase 16 should remove residual metric-box styling after mobile QA');
assert.match(css, /v1\.48 - Phase 17 one-primary-action hierarchy with restrained SF-style line icons/, 'Phase 17 one-primary-action icon hierarchy marker required');
assert.match(css, /v1\.48\.1 - Phase 17 no-black-slab command correction/, 'Phase 17 should remove heavy black command slabs after screenshot QA');
assert.match(css, /v1\.48\.2 - Phase 17 no-black control slabs/, 'Phase 17 should remove remaining black control slabs after closing QA');
assert.match(css, /v1\.48\.3 - Phase 17 soften document step numerals/, 'Phase 17 should soften residual black document numerals after closing QA');
assert.match(css, /v1\.49 - Phase 17B Apple-industrial information hierarchy refinement/, 'Phase 17B refined hierarchy marker required');
assert.match(css, /v1\.49\.1 - Phase 17B closing de-nesting and proof-row quieting/, 'Phase 17B should include closing de-nesting after screenshot QA');
assert.match(css, /v1\.49\.2 - Phase 17B operational completion color system/, 'Phase 17B should restore at-a-glance done\/todo color states');
assert.match(css, /\.validation-queue-item\.is-emailed[\s\S]{0,260}border-left-color: var\(--done-accent\)/, 'Emailed builder rows need an immediate visual completion rail');
assert.match(css, /v1\.50 - Phase 18 decision-spine readability refinement/, 'Phase 18 decision-spine marker required');
assert.match(css, /v1\.50\.1 - Phase 18 mobile decision spine correction/, 'Phase 18 should correct mobile decision-spine alignment after screenshot QA');
assert.match(css, /v1\.50\.2 - Phase 18 mobile icon discipline/, 'Phase 18 should remove decorative primary-strip icons on mobile when they compete with scan clarity');
assert.match(css, /v1\.50\.3 - Phase 18 mobile action label safe inset/, 'Phase 18 should keep mobile primary-action labels clear of the decision rail');
assert.match(css, /v1\.51 - Phase 19 premium forest\/gold calm system and border reduction/, 'Phase 19 premium forest/gold border-reduction marker required');
assert.match(css, /v1\.51\.1 - Phase 19 screenshot correction: no dark control slabs, no clipped decision labels/, 'Phase 19 should correct screenshot-found dark controls and clipped decision labels');
assert.match(css, /v1\.51\.2 - Phase 19 mobile remove rail collisions and source-row rule noise/, 'Phase 19 should remove mobile rail collisions and excess source row rules after screenshot QA');
assert.match(css, /v1\.51\.3 - Phase 19 call\/email contact indicators/, 'Phase 19 should style call/email and called/emailed indicators as readable state chips');
assert.match(css, /v1\.52 - Phase 20 pure Apple-aesthetic hierarchy refinement/, 'Phase 20 pure Apple-aesthetic refinement marker required');
assert.match(css, /v1\.52\.1 - Phase 20 screenshot correction: no active-tab slabs, no dark sticky dock/, 'Phase 20 should correct screenshot-found nav slabs and dark mobile dock');
assert.match(css, /v1\.52\.2 - Phase 20 mobile chrome hardening/, 'Phase 20 should harden mobile chrome after screenshot QA');
assert.match(css, /v1\.53 - Phase 21 builder contact ledger rail/, 'Phase 21 should add the Builders state contact ledger rail styling');
assert.match(css, /v1\.53\.1 - Phase 21 screenshot correction: readable two-line ledger cards/, 'Phase 21 should keep ledger-card copy readable after screenshot QA');
assert.match(css, /\.builder-ops-header \.market-toggle \.market-contact-rail[\s\S]{0,260}background: rgba\(16,23,21,\.105\)/, 'contact rail should use a quiet open segment instead of a busy progress bar');
assert.match(css, /\.builder-ops-header \.market-toggle \.market-contact-rail i[\s\S]{0,260}width: var\(--contact-progress, 0%\)/, 'contact rail fill should be driven by state-specific progress percentage');
assert.match(css, /v1\.54 - Phase 22 Apple review scan hierarchy and fatigue reduction/, 'Phase 22 Apple review scan hierarchy marker required');
assert.match(css, /v1\.54\.1 - Phase 22 screenshot correction: unclipped builder state grid/, 'Phase 22 should correct screenshot-found builder state clipping');
assert.match(css, /--phase22-scan-rule: calm-open-canvas-ledger-density-no-dark-code-slabs/, 'Phase 22 should encode the design rule: no dark code slabs, no card-dashboard density');
assert.match(css, /--phase22-forest: #0d6044/, 'Phase 22 should refine forest accent token');
assert.match(css, /--phase22-gold: #8c6513/, 'Phase 22 should refine gold metric token');
assert.match(css, /body\[data-active-view="machine"\] main :where\(pre, code, \.code-block, \.csv-preview, \.template-preview, \.import-preview\)[\s\S]{0,220}background: #f2f2ed !important;/, 'Machine code/import surfaces should be light ledger surfaces, not black fatigue slabs');
assert.match(css, /#app \.builder-ops-header \.market-toggle-grid::-webkit-scrollbar \{ display: none !important; \}/, 'Builders mobile ledger carousel should hide native scrollbars');
assert.match(css, /\.app-panel\[hidden\],[\s\S]{0,320}#workspace\[hidden\][\s\S]{0,80}display: none !important;/, 'Phase 22 route isolation guard must stay last after late visual overrides');
assert.match(css, /--apple-review-rule-phase20: pure-apple-canvas-no-slabs-no-decorative-boxes/, 'Phase 20 should encode the Apple review rule against slabs and decorative boxes');
assert.match(css, /--phase20-measure: 62ch/, 'Phase 20 should tighten dense reading measure for sensor-friendly long sessions');
assert.match(css, /navigation is orientation, never a competing control slab/, 'Phase 20 should quiet nav into orientation rather than a control slab');
assert.match(css, /#app :where\(\.wk-hero,[\s\S]{0,480}background: transparent !important;[\s\S]{0,280}box-shadow: none !important/, 'Phase 20 should remove decorative section slabs from the Apple canvas');
assert.match(css, /body\[data-active-view="today"\] #command \.wk-actions[\s\S]{0,420}border-top: 1px solid rgba\(15,95,68,\.22\)/, 'Phase 20 should turn Today actions into quiet native rows');
assert.match(css, /Final route isolation guard after Phase 20 product-wide layout overrides/, 'Phase 20 should preserve route isolation after product-wide overrides');
assert.match(css, /--brand-forest-900: #0d3328/, 'Phase 19 should define a deep accessible forest primary brand color');
assert.match(css, /--brand-gold-700: #7c5311/, 'Phase 19 should define a contrast-safe gold highlight color');
assert.match(css, /--purposeful-boundaries-only: true/, 'Phase 19 should encode the no-purposeless-borders rule');
assert.match(css, /Remove purposeless rule stacks[\s\S]{0,420}border-bottom: 0 !important/, 'Phase 19 should remove decorative stacked horizontal rules from section starts');
assert.match(css, /Legend becomes dots, not another set of rules/, 'Phase 19 should simplify status legends from line bars to calm dots');
assert.match(css, /Final route isolation guard after display\/layout overrides/, 'Phase 19 should keep hash-route isolation after late layout overrides');
assert.match(css, /--phase18-reading-measure: 68ch/, 'Phase 18 should constrain dense body copy to a sensor-friendly reading measure');
assert.match(css, /Apple review rule: one decision spine per screen, evidence below, optional depth last/, 'Phase 18 should encode the decision-spine hierarchy rule');
assert.match(css, /completion-state-legend[\s\S]{0,260}legend-done/, 'Phase 18 should include a calm state legend for done, working, and todo');
assert.match(css, /#app :where\(\.validation-source-proof,\.wk-proof-grid,\.builder-ops-metrics[\s\S]{0,300}border-top: 1px solid var\(--phase18-hairline\)/, 'Phase 18 should turn dense evidence grids into hairline ledgers');
assert.match(css, /Apple review rule: one obvious action, then quiet evidence, then optional depth/, 'Phase 17B should encode the Apple review hierarchy rule');
assert.match(css, /#app \.primary-action-strip[\s\S]{0,520}grid-template-columns: minmax\(104px, \.26fr\) minmax\(0, 1fr\) auto !important/, 'Phase 17B should tighten the primary action strip into a calmer Swiss ledger');
assert.match(css, /\.product-icon[\s\S]{0,420}stroke-width: var\(--icon-stroke\)/, 'Phase 17 should use restrained stroke icons, not decorative icon boxes');
assert.match(css, /\.primary-action-strip[\s\S]{0,760}grid-template-columns: minmax\(140px, \.42fr\) minmax\(0, 1fr\) auto/, 'Phase 17 should introduce a consistent primary-action strip hierarchy');
assert.match(css, /Apple review rule: one obvious action, then evidence/, 'Phase 17 should de-emphasize secondary evidence after the primary action');
assert.match(css, /--font-heavy-text: 'Inter'/, 'Phase 16 should use Inter/SF-style sans for dense technology-app reading');
assert.match(css, /#app :where\(\.wk-workbench,[\s\S]{0,1400}border-top: 1px solid var\(--ledger-rule\) !important/, 'Phase 16 should replace nested modules with open ledger rules');
assert.match(css, /body\[data-active-view="today"\] #command \.wk-rail \{ display: none !important; \}/, 'Phase 16 should remove Today rail chrome from first-screen cognition');
assert.match(css, /#app \.app-panel\[hidden\]/, 'Phase 16 route isolation guard should remain after late layout overrides');
assert.match(html, /One seller\. One reason\. One next move\./, 'Deal page copy should be compressed into one-action hierarchy');
assert.match(html, /Buyer demand first\./, 'Builder page copy should make the hierarchy buyer-first');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /function productIcon\(kind\)[\s\S]{0,1400}class="product-icon"/, 'Phase 17 product icon helper should be present in app source');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /primary-action-strip builders-primary-action[\s\S]{0,80}<span>Next action<\/span>[\s\S]{0,220}Call the highest-signal builder/, 'Builders should expose a clear next-action strip before secondary evidence');
assert.doesNotMatch(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /primary-action-strip[\s\S]{0,80}\$\{productIcon\('[^']+'\)\} Do first|>Start queue /, 'Primary action strips should not use vague Do first timeline-icon labeling');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /is-emailed[\s\S]{0,160}needs-email/, 'Builder queue rows should add emailed/todo completion classes for visual scanning');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /data-email-state="\$\{outreach\.email \? 'done' : 'todo'\}"/, 'Builder queue rows should expose machine-readable email completion state');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /completion-state-legend[\s\S]{0,160}legend-working[\s\S]{0,120}legend-todo/, 'Builder command center should explain done, in-progress, and todo state colors');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /contact-call[\s\S]{0,520}solidIndustryIcon\('phone'\)[\s\S]{0,260}contact-email[\s\S]{0,520}solidIndustryIcon\('email'\)/, 'Builder queue should expose readable phone/email icon indicators with aria labels, not visible completion text');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /primary-action-strip closing-primary-action[\s\S]{0,260}Clear the title packet/, 'Closing should expose one primary action before secondary evidence');
assert.doesNotMatch(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /Phase 12 · Print detail finish/, 'Closing document packet should not expose implementation-phase residue');
assert.doesNotMatch(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /Phase 8 · real operator session mode/, 'Today route should not expose implementation-phase residue');
const roundedButtonRules = [...css.matchAll(/([^{}]*button[^{}]*)\{([^{}]*border-radius[^{}]*)\}/g)]
  .filter(match => !/border-radius:\s*0\s*!important/.test(match[2]));
assert.deepEqual(roundedButtonRules.map(match => match[1].trim()).slice(0, 5), [], 'No button selector may retain rounded corner radius');
assert.match(css, /v1\.55 - Phase 23 Apple hierarchy correction: compact chrome, Today cleanup, buy-box form, closing disclosure/, 'Phase 23 marker required for the Apple hierarchy correction pass');
assert.match(css, /--brand-forest: #194d36/, 'Phase 23 should define the premium forest primary accent');
assert.match(css, /--brand-gold: #b68a2c/, 'Phase 23 should define the restrained gold metric highlight');
assert.match(css, /header\.nav[\s\S]{0,180}min-height: 44px !important/, 'Phase 23 should correct excessive desktop nav height');
assert.match(css, /@media \(max-width: 760px\)[\s\S]{0,220}min-height: 46px !important/, 'Phase 23 should override the old tall mobile nav grid');
assert.match(css, /body\[data-active-view="today"\] #command \.wk-hero::before,[\s\S]{0,180}display: none !important/, 'Phase 23 should remove Today legacy field/proof-surface chrome');
assert.match(css, /\.validation-form\.validation-buybox-grid[\s\S]{0,260}grid-template-columns: repeat\(12, minmax\(0, 1fr\)\)/, 'Phase 23 should rebuild the buy-box form as a structured settings sheet');
assert.match(css, /\.validation-buybox-grid :where\(input, select, textarea\)[\s\S]{0,360}background: transparent !important;[\s\S]{0,160}border: 0 !important/, 'Buy-box fields should not look like raw 90s HTML input boxes');
assert.match(css, /\.contract-disclosure-experience:not\(\[open\]\) > :not\(summary\)[\s\S]{0,80}display: none !important/, 'Closing seller/buyer documents should use progressive disclosure');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /<details id="seller-agreement-experience"[\s\S]{0,220}contract-disclosure-summary/, 'Seller Agreement should render as a collapsible disclosure');
assert.match(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /<details id="assignment-agreement-experience"[\s\S]{0,220}contract-disclosure-summary/, 'Assignment Agreement should render as a collapsible disclosure');
assert.match(css, /v1\.55\.1 - Phase 23 screenshot correction: single-row mobile nav and no Today field relics/, 'Phase 23 screenshot correction marker required');
assert.match(css, /\.app-tabs,[\s\S]{0,220}flex-wrap: nowrap !important/, 'Mobile nav tabs should remain single-row and horizontally scroll instead of forcing a tall grid');
assert.doesNotMatch(readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8'), /Terrain intelligence \/ Tennessee live-first|TN terrain|builder demand, parcel constraint/, 'Today route should not keep old terrain/campaign wording relics');
assert.match(css, /v1\.56 - Phase 24 Apple product-system Today rebuild: forest\/gold calm hierarchy, no legacy display relics/, 'Phase 24 marker required for the Apple product-system Today rebuild');
assert.match(css, /--phase24-forest: #164d36/, 'Phase 24 should define an accessible forest primary accent');
assert.match(css, /--phase24-gold: #9c741f/, 'Phase 24 should define a restrained gold metric highlight');
assert.match(css, /--phase24-rule: every-pixel-earns-place-one-primary-action-calm-evidence-after/, 'Phase 24 should encode the hierarchy rule');
assert.match(css, /body\[data-active-view="today"\] #command :where\(\.wk-rail,\.wk-progress,\.legacy-proof-surface,\.legacy-proof-rule,\.legacy-proof-axis,\.legacy-proof-ring\)[\s\S]{0,90}display: none !important/, 'Phase 24 should hard-remove Today rail/proof/sign relic chrome');
assert.match(css, /body\[data-active-view="today"\] #command \.phase24-snapshot div[\s\S]{0,260}border-bottom: 1px solid var\(--phase24-line\)/, 'Today snapshot should be a ledger, not another boxed dashboard tile');
assert.match(css, /Final route isolation guard after Phase 24 Today rebuilding/, 'Phase 24 should preserve route isolation after late Today overrides');
const appSource = readFileSync(new URL('../src/app.mjs', import.meta.url), 'utf8');
const coreSource = readFileSync(new URL('../src/core.mjs', import.meta.url), 'utf8');
const todaySource = appSource.slice(appSource.indexOf('function renderCommandCenter'), appSource.indexOf('function initializeEditorialMotion'));
assert.match(todaySource, /phase24-today-hero[\s\S]{0,240}Make the clearest next move\./, 'Today should render the new Phase 24 operating hero');
assert.match(todaySource, /phase24-snapshot[\s\S]{0,260}Builder proof/, 'Today should replace decorative artifact chrome with a proof snapshot');
assert.doesNotMatch(todaySource, /wk-artifact|wk-scanline|wk-horizon|wk-contour|Today page map|Signal system|Market terrain|terrain intelligence|\bwells\b|\bwall\b/i, 'Today render path must not keep old relics');
assert.doesNotMatch(appSource, /one long wall/i, 'Product copy should not describe dense surfaces as a wall');
assert.doesNotMatch(appSource + html, /source map|independent wells|resource wells|first resource well|velocity well|Piedmont well|high-volume well/i, 'Phase 24 should replace map/well signage with calm source-lane language');
assert.match(appSource + html, /Source lanes|Queued lanes|source lane/, 'Phase 24 should use source-lane language consistently');
assert.match(css, /v1\.57 - Phase 25 Apple design review pass: calm ledger hierarchy, serious solid icons, tooltip depth/, 'Phase 25 Apple design-review marker required');
assert.match(css, /--phase25-review-rule: apple-calm-ledger-one-primary-scent-secondary-depth-in-tooltips/, 'Phase 25 should encode calm hierarchy and tooltip-depth rule');
assert.match(css, /--phase25-forest: #124d35/, 'Phase 25 should define an accessible forest primary accent');
assert.match(css, /--phase25-gold: #8f6819/, 'Phase 25 should define a contrast-safe gold metric accent');
assert.match(appSource, /function solidIndustryIcon\(kind\)[\s\S]*class="solid-industry-icon"/, 'Phase 25/29 should use serious solid product icons instead of decorative indicators');
assert.doesNotMatch(appSource, /queue-proof-line|queue-source-link/, 'Builder queue should not repeat source/proof detail already shown in selected builder detail');
assert.match(appSource, /validation-source-proof[\s\S]{0,260}safeLink\(selected\.sourceUrl/, 'Selected builder detail should retain the source proof link');
assert.match(appSource, /queue-score[\s\S]{0,180}solidIndustryIcon\('score'\)/, 'Builder score should use the solid icon language');
assert.match(appSource, /contact-icon-toggle contact-call[\s\S]{0,420}solidIndustryIcon\('phone'\)[\s\S]{0,80}<\/button>/, 'Call log toggle should keep the phone icon; color state is enough');
assert.match(appSource, /contact-icon-toggle contact-email[\s\S]{0,420}solidIndustryIcon\('email'\)[\s\S]{0,80}<\/button>/, 'Email log toggle should keep the email icon; color state is enough');
assert.match(appSource, /validation-script-drawer[\s\S]{0,180}solidIndustryIcon\('chevron'\)/, 'Disclosure drawers should use a restrained solid chevron icon');
assert.match(css, /\.validation-script-drawer:not\(\[open\]\) > :not\(summary\)[\s\S]{0,80}display: none !important/, 'Phase 25 should keep secondary scripts hidden until requested');
const builderCommandSource = appSource.slice(appSource.indexOf('function renderBuyerValidationCommand'), appSource.indexOf('function renderBuilderMarketWorkbench'));
assert.doesNotMatch(builderCommandSource, /Selected resource well|resource well|permit signals/i, 'Visible builder command copy should remove resource-well/signaling relics');
assert.match(css, /Final route isolation guard after Phase 25 Apple design review pass/, 'Phase 25 should preserve route isolation after late visual overrides');
assert.match(css, /v1\.57\.1 - Phase 25 screenshot correction: queue controls are icon-only, no cramped CALL\/EMAIL text/, 'Phase 25 screenshot correction should prevent cramped queue contact labels');
assert.match(css, /\.validation-queue \.contact-icon-toggle em[\s\S]{0,220}clip: rect\(0 0 0 0\) !important/, 'Queue contact text should be visually hidden while aria labels carry meaning');
assert.match(css, /v1\.58 - Phase 26 Apple HIG refinement: short labels, tooltip depth, calmer dense hierarchy/, 'Phase 26 Apple HIG refinement marker required');
assert.match(css, /--phase26-review-rule: short-visible-labels-secondary-detail-lives-in-tooltip/, 'Phase 26 should encode short labels and tooltip-depth rule');
assert.match(css, /--phase26-forest: #104b33/, 'Phase 26 should define accessible forest primary accent');
assert.match(css, /--phase26-gold: #866014/, 'Phase 26 should define contrast-safe gold metric accent');
assert.match(appSource, /<span>Queue <button[\s\S]{0,280}<b title="Source URLs, permit counts, confidence, and score detail sit in row tooltips/, 'Queue header should use short visible labels with tooltip depth');
assert.match(appSource, /<span class="eyebrow">Builder<\/span>/, 'Selected builder label should be shortened to Builder');
assert.match(appSource, /<div class="next-best-action"><span>Next<\/span>/, 'Next best action label should be shortened to Next');
assert.match(appSource, /<span>Seller gate<\/span><b>\$\{selected\.sellerSearch\?\.eligible \? 'open'/, 'Seller gate label/status should be short');
assert.match(appSource, /<summary><span>Questions \+ script<\/span>\$\{solidIndustryIcon\('chevron'\)\}<\/summary>/, 'Call script drawer should use shorter summary copy');
assert.match(appSource, /<summary><span>Intro email<\/span>\$\{solidIndustryIcon\('chevron'\)\}<\/summary>/, 'Marketing drawer should use shorter summary copy');
assert.doesNotMatch(appSource + coreSource, /resource well|Resource well|permit signals|Selected builder|Next best action|Seller search gate|Optional marketing intro email template|Exact buy-box questions \+ call script/, 'Phase 26 should remove remaining long/relic visible labels');
assert.match(coreSource, /label: 'Permit proof'[\s\S]{0,900}label: 'Review hold'/, 'Score breakdown labels should be short and proof-based');
assert.match(coreSource, /Live source lane|Source lane/, 'Source metadata should harmonize old well language into source-lane language');
assert.match(css, /Final route isolation guard after Phase 26 Apple HIG refinement/, 'Phase 26 should preserve route isolation after late visual overrides');
assert.match(css, /v1\.58\.1 - Phase 26 QA correction: reduce desktop dead air before the validation cockpit/, 'Phase 26 QA correction should reduce dead air before the validation cockpit');


assert.match(css, /v1\.59 - Phase 27 Closing-first Apple HIG cleanup: no surface\/orbit\/field relics, calm ledger hierarchy/, 'Phase 27 Closing cleanup marker required');
assert.match(css, /--phase27-forest: #104b33/, 'Phase 27 should preserve accessible forest accent');
assert.match(css, /--phase27-gold: #896116/, 'Phase 27 should preserve restrained gold metric accent');
assert.match(appSource, /<div class="closing-hero">/, 'Closing hero should use product-native class naming, not title/orbit language');
assert.match(appSource, /class="closing-card checklist-card"/, 'Closing cards should use product-native card class naming');
assert.doesNotMatch(appSource, /title-orbital-hero|title-glass-card|title-command-card|title-metric-strip/, 'Closing app markup must not keep old title/orbit/surface class relics');
assert.doesNotMatch(css, /--glass|--glass-dark|--terrain-|wk-artifact|wk-scanline|wk-horizon|wk-contour|title-orbital-hero|title-glass-card|title-command-card|font-family: Georgia, 'Times New Roman', serif/, 'Stylesheet must not keep token-level Closing/Today typographic relics');
assert.match(css, /body\[data-active-view="closing"\] \.closing-hero-copy h2[\s\S]{0,420}font-family: var\(--font-grotesk\) !important/, 'Closing heading should use the Grotesk product type system');
assert.match(css, /Final route isolation guard after Phase 27 Closing cleanup/, 'Phase 27 should preserve route isolation after late Closing overrides');

assert.match(appSource, /field-label-text"><span>\$\{h\(label\)\}<\/span><em aria-hidden="true" title="Required">\*<\/em><\/span>/, 'Required buy-box form marks should sit directly after the label text');
assert.doesNotMatch(appSource, /required field\(s\) left|required seller field\(s\) left|required gate\(s\) left|buyer field\(s\) left|buyer gate\(s\) left|>\$\{complete \? '✓' : 'required'\}<\/em>|field-helper">Required\.|\$\{complete \? 'Done' : '\*'\}/, 'Visible form status copy should not spell out required or Done; use label-adjacent * only');

assert.match(css, /v1\.60 - Phase 28 Apple product-system convergence: Closing ledger, unified SF\/Inter typography, no legacy display-font relics/, 'Phase 28 product-system convergence marker required');
assert.match(css, /--phase28-forest: #0f4d35/, 'Phase 28 should define premium accessible forest accent');
assert.match(css, /--phase28-gold: #8a6418/, 'Phase 28 should define restrained gold highlight accent');
assert.match(css, /body\[data-active-view="closing"\] \.closing-hero[\s\S]{0,520}linear-gradient\(145deg, #fffef8 0%, #f5f0e4 100%\)/, 'Closing hero should be brought into the calm light Apple ledger paradigm');
assert.match(css, /body\[data-active-view="closing"\] \.contract-flow-workspace[\s\S]{0,260}background: transparent !important/, 'Closing contract workspace should remove excess nested card chrome');
assert.match(css, /#closing-desk\[hidden\][\s\S]{0,120}display: none !important/, 'Phase 28 route isolation guard should protect hidden routed pages');
assert.doesNotMatch(css, /Fraunces|Georgia|Times New Roman|Archivo|wk-serif|wk-sans|wk-meta/, 'Old stylistic font families and token names must be removed from the stylesheet');
assert.doesNotMatch(appSource + css, /title-orbital|title-glass|title-command-card|resource well|permit signals|\bsignage\b|\bbillboard\b|wk-artifact|wk-scanline|wk-contour/, 'Wall/sign-era product relics must not remain in app markup or stylesheet');

assert.match(css, /v1\.61 - Phase 29 Apple review: old colors\/icons\/effects removed, designed empty states, responsive nav repair/, 'Phase 29 Apple review marker required');
assert.doesNotMatch(css, /fonts\.googleapis\.com|DM\+Mono|Space\+Grotesk|#2563eb|#174ea6|#9fe870|#ff6b57|rgba\(159,232,112|rgba\(37,99,235/, 'Old stylistic fonts and old blue/neon/coral color literals must not remain');
assert.match(appSource, /closing-empty-state designed-empty-state[\s\S]{0,260}empty-state-icon[\s\S]{0,260}Select a buyer-backed deal to open escrow work/, 'Closing empty state should be a designed guided surface, not a confusing blank card');
assert.match(appSource, /disclosure-news-icon[\s\S]{0,140}solidIndustryIcon\('disclosure'\)/, 'Closing expanding document components should use the loved document/news icon treatment');
assert.match(appSource, /solidIndustryIcon\('check'\)[\s\S]{0,100}: solidIndustryIcon\('pending'\)/, 'Old raw completion glyph icons should be replaced by product SVG icons');
assert.match(css, /body\[data-active-view="today"\][\s\S]{0,420}linear-gradient\(180deg, var\(--phase29-canvas\)/, 'Today should use calm canvas instead of old background effects');
assert.match(css, /body\[data-active-view="today"\] #command :where\([\s\S]{0,220}\.map-glow[\s\S]{0,260}display: none !important/, 'Today old glow/map background effects should be suppressed');
assert.match(css, /--phase29-nav-rule: desktop-responsive-tabs-wrap-without-clipping/, 'Phase 29 should encode the desktop responsive navbar repair');
assert.match(css, /v1\.61\.1 - Phase 29 hotfix: visible wrapping nav and text-only builder log toggles/, 'Phase 29 hotfix marker required after nav visibility regression');
assert.match(css, /v1\.61\.2 - Nav visibility hard guard: no route item can hide in historical app-tabs scrollers/, 'Final nav hard guard required after legacy app-tabs scrollers broke navigation');
assert.match(css, /--phase29-nav-hard-guard: route-tabs-visible-after-all-legacy-nav-blocks/, 'Final nav guard should encode route-tab visibility after all legacy nav blocks');
assert.match(css, /html body \.nav \.app-tabs[\s\S]{0,320}overflow-x: visible !important;[\s\S]{0,180}max-width: none !important;[\s\S]{0,120}white-space: normal !important/, 'Final nav guard must beat historical app-tabs overflow scrollers');
assert.match(css, /--phase29-hotfix-nav-rule: all-route-tabs-visible-no-hidden-scroller/, 'Hotfix should encode visible route tabs rather than a hidden scroller');
assert.match(css, /v1\.61\.3 - Phase 29 correction: restore original nav rail spacing and icon-only call\/email log controls/, 'Phase 29 correction marker required for clarified nav/log-button intent');
assert.match(css, /--phase29-nav-correction-rule: original-nav-rail-equal-side-spacing-only/, 'Nav correction should restore the old rail and only fix equal side spacing');
assert.match(css, /html body \.nav[\s\S]{0,260}grid-template-columns: minmax\(120px, 1fr\) auto minmax\(120px, 1fr\) !important;[\s\S]{0,240}padding-left: clamp\(18px, 4vw, 42px\) !important;[\s\S]{0,120}padding-right: clamp\(18px, 4vw, 42px\) !important/, 'Navbar should use the original centered rail with equal left/right spacing');
assert.doesNotMatch(css, /\.app-tabs \{[\s\S]{0,260}max-width: min\(720px, 58vw\) !important;[\s\S]{0,220}overflow-x: auto !important/, 'Broken Phase 29 hidden-scroll nav pattern must not be the active nav rule');
assert.match(css, /--phase29-log-correction-rule: phone-email-icons-only-no-check-no-visible-text/, 'Log toggle correction should preserve icons but remove explicit text/check indicators');
assert.match(appSource, /contact-icon-toggle contact-call[\s\S]{0,460}solidIndustryIcon\('phone'\)[\s\S]{0,90}<\/button>/, 'Builder queue call log toggle should be icon-only with phone icon');
assert.match(appSource, /contact-icon-toggle contact-email[\s\S]{0,460}solidIndustryIcon\('email'\)[\s\S]{0,90}<\/button>/, 'Builder queue email log toggle should be icon-only with email icon');
assert.match(appSource, /selected-outreach-state[\s\S]{0,1000}contact-state-toggle[\s\S]{0,900}solidIndustryIcon\('phone'\)[\s\S]{0,900}contact-state-toggle[\s\S]{0,900}solidIndustryIcon\('email'\)/, 'Builder detail logging toggles should keep phone/email icons');
assert.doesNotMatch(appSource, /contact-icon-toggle contact-call[\s\S]{0,520}<em>|contact-icon-toggle contact-email[\s\S]{0,520}<em>|contact-state-toggle[\s\S]{0,360}solidIndustryIcon\('check'\)/, 'Builder queue/detail logging toggles should not show explicit text or check icons');
assert.doesNotMatch(css, /contact-(?:icon|state)-toggle\[data-toggle-validation-contact="email"\]\.is-on span::after[\s\S]{0,160}content:\s*['"]✓['"]/, 'Active email logging controls must keep the email icon but must not add a checkmark pseudo-element');
assert.match(css, /contact-icon-toggle\[data-toggle-validation-contact="email"\]\.is-on span::after,[\s\S]{0,120}content: none !important;[\s\S]{0,80}display: none !important/, 'Email logging checkmark pseudo-element should be explicitly suppressed');
assert.match(css, /v1\.61\.5 - Apple-grade builder validation form: flat settings sheet, label-adjacent required marks/, 'Form redesign marker required after screenshot correction');
assert.match(css, /--phase29-form-rule: apple-flat-settings-sheet-label-adjacent-required-mark/, 'Form redesign should encode the flat Apple settings-sheet rule');
assert.match(css, /body\[data-active-view="builders"\] \.validation-buybox-grid \.form-field[\s\S]{0,520}border-right: 1px solid rgba\(16, 23, 19, \.085\) !important;[\s\S]{0,180}background: transparent !important;[\s\S]{0,120}box-shadow: none !important/, 'Buy-box fields should be flat cells with hairlines, not nested cards');
assert.match(css, /body\[data-active-view="builders"\] \.validation-buybox-grid input,[\s\S]{0,420}border: 0 !important;[\s\S]{0,120}border-radius: 0 !important;[\s\S]{0,180}background: transparent !important/, 'Buy-box inputs should not create a second nested box inside the field cell');
assert.match(css, /body\[data-active-view="builders"\] \.validation-buybox-grid \.field-label-text[\s\S]{0,260}display: inline-flex !important;[\s\S]{0,140}gap: 4px !important/, 'Required star should be visually associated immediately after the label');
assert.match(css, /v1\.61\.6 - Apple HIG correction: primary action is an instruction bar, not a fake timeline hero/, 'Apple HIG action-strip correction marker required');
assert.match(css, /--phase29-action-strip-rule: compact-next-action-bar-no-timeline-rail/, 'Action strips should encode compact next-action bar rule');
assert.match(css, /v1\.61\.6 - Apple HIG correction[\s\S]{0,1800}#app \.primary-action-strip::before,[\s\S]{0,900}content: none !important;[\s\S]{0,80}display: none !important/, 'Primary action strips must not draw fake timeline rail pseudo-elements');
assert.match(css, /#app \.primary-action-strip > span \.product-icon,[\s\S]{0,260}display: none !important/, 'Primary action strip labels should not include decorative status icons');
assert.match(css, /#app \.primary-action-strip > b,[\s\S]{0,260}font: 690 clamp\(17px, 1\.45vw, 21px\)\/1\.22/, 'Primary action copy should be compact instruction text, not a billboard hero');
assert.match(css, /v1\.62 - Phase 30 Today \+ Sources Apple information hierarchy: calm typography, premium forest\/gold, no nested noise/, 'Phase 30 Today/Sources marker required');
assert.match(css, /--phase30-rule: today-sources-only-calm-premium-information-hierarchy/, 'Phase 30 must encode that refinement is scoped to Today and Sources');
assert.match(css, /--phase30-forest: #123f2e/, 'Phase 30 should define a refined accessible forest primary');
assert.match(css, /--phase30-gold: #9a741e/, 'Phase 30 should define a restrained premium gold metric accent');
assert.match(css, /--phase30-reading: 66ch/, 'Phase 30 should constrain dense supporting copy to a comfortable reading measure');
assert.match(css, /body\[data-active-view="today"\] #command \.phase24-today-hero[\s\S]{0,520}border-bottom: 1px solid var\(--phase30-line\) !important;[\s\S]{0,220}background: transparent !important;[\s\S]{0,180}box-shadow: none !important/, 'Today hero should be a calm command surface, not a decorated slab');
assert.match(css, /body\[data-active-view="today"\] #command \.phase24-snapshot div[\s\S]{0,420}grid-template-columns: minmax\(116px, \.52fr\) minmax\(0, 1fr\) auto !important/, 'Today metrics should read as a scan-friendly ledger');
assert.match(css, /body\[data-active-view="today"\] #command :where\(\.phase24-market-list,\.phase24-proof-grid,\.phase24-work-grid\)[\s\S]{0,260}background: transparent !important/, 'Today dense grids should not carry nested boxed backgrounds');
assert.match(css, /body\[data-active-view="sources"\] #sources-hub > \.section-heading[\s\S]{0,520}border-bottom: 1px solid var\(--phase30-line\) !important;[\s\S]{0,180}background: transparent !important;[\s\S]{0,100}box-shadow: none !important/, 'Sources heading should be a flat editorial header, not a hero card');
assert.match(css, /body\[data-active-view="sources"\] #sources-hub \.source-priority-board[\s\S]{0,420}grid-template-columns: minmax\(0, \.82fr\) minmax\(300px, \.5fr\) !important/, 'Sources priority board should use a purposeful two-column hierarchy');
assert.match(css, /body\[data-active-view="sources"\] #sources-hub \.pipeline[\s\S]{0,320}grid-template-columns: repeat\(7, minmax\(0, 1fr\)\) !important;[\s\S]{0,220}background: transparent !important/, 'Sources pipeline should be a compact seven-stage ledger, not a cluster of cards');
assert.match(css, /body\[data-active-view="sources"\] #sources-hub :where\(\.badge,\.tags span,\.source-meta code,\.permit-platform-tags em\)[\s\S]{0,220}background: var\(--phase30-green-soft\) !important/, 'Sources chips should use restrained forest information scent');
assert.match(css, /v1\.62\.1 - Phase 30 QA correction: Sources hero reads as one left-to-right editorial block/, 'Phase 30 Sources screenshot QA correction marker required');
assert.match(css, /body\[data-active-view="sources"\] #sources-hub > \.section-heading[\s\S]{0,180}grid-template-areas:[\s\S]{0,160}"kicker support"[\s\S]{0,80}"title support" !important/, 'Sources desktop header should keep kicker/title together instead of splitting the title to the right column');
assert.match(css, /v1\.62\.2 - Phase 30 QA correction: Sources next action must not squeeze into word-by-word columns/, 'Phase 30 Sources action-strip screenshot QA correction marker required');
assert.match(css, /body\[data-active-view="sources"\] #sources-hub \.sources-primary-action[\s\S]{0,160}grid-template-columns: 1fr !important/, 'Sources next-action strip should give the instruction full reading width instead of squeezing into columns');
assert.match(css, /v1\.63 - Phase 31 Builders Apple hierarchy: buyer validation as one calm work surface/, 'Phase 31 Builders marker required');
assert.match(css, /--phase31-builders-rule: builders-only-calm-buyer-validation-ledger/, 'Phase 31 must encode Builders-only scope');
assert.match(css, /--phase31-forest: #123f2e/, 'Phase 31 should reuse accessible premium forest primary for Builders');
assert.match(css, /--phase31-gold: #9a741e/, 'Phase 31 should use restrained gold for Builder scores/key metrics');
assert.match(css, /body\[data-active-view="builders"\] \.builder-ops-header[\s\S]{0,520}border-bottom: 1px solid var\(--phase31-line\) !important;[\s\S]{0,220}background: transparent !important;[\s\S]{0,160}box-shadow: none !important/, 'Builders header should be an open editorial command surface');
assert.match(css, /body\[data-active-view="builders"\] \.market-toggle-grid[\s\S]{0,320}border-top: 1px solid var\(--phase31-line\) !important;[\s\S]{0,260}background: transparent !important;[\s\S]{0,120}box-shadow: none !important/, 'Builder market switcher should be a flat ledger, not a boxed card cluster');
assert.match(css, /body\[data-active-view="builders"\] \.validation-command[\s\S]{0,460}border-top: 1px solid var\(--phase31-line\) !important;[\s\S]{0,220}background: transparent !important;[\s\S]{0,140}box-shadow: none !important/, 'Builder validation command should be one calm work surface, not nested dashboards');
assert.match(css, /body\[data-active-view="builders"\] \.validation-grid-main[\s\S]{0,220}grid-template-columns: minmax\(300px, \.42fr\) minmax\(0, 1fr\) minmax\(250px, \.34fr\) !important/, 'Builder queue/detail/seller gate should use a purposeful three-column work ledger');
assert.match(css, /body\[data-active-view="builders"\] \.validation-focus-head h3[\s\S]{0,240}font: 730 clamp\(38px, 4\.8vw, 68px\)\/\.92/, 'Selected builder title should be strong but not billboard-scale');
assert.match(css, /body\[data-active-view="builders"\] \.validation-buybox-grid input,[\s\S]{0,420}border: 0 !important;[\s\S]{0,120}background: transparent !important/, 'Builder buy-box inputs should remain flat and high-legibility');
assert.match(css, /v1\.63\.1 - Phase 31 QA correction: tighter Builders cadence, readable market ledger, semantic progress colors/, 'Phase 31 Builders screenshot QA correction marker required');
assert.match(css, /body\[data-active-view="builders"\] \.market-toggle em,[\s\S]{0,120}body\[data-active-view="builders"\] \.market-toggle \.market-builder-total[\s\S]{0,220}white-space: normal !important/, 'Builder market counts must wrap cleanly instead of colliding');
assert.match(css, /body\[data-active-view="builders"\] \.completion-state-legend \.legend-working[\s\S]{0,80}color: var\(--phase31-gold\) !important/, 'Builder progress legend must preserve distinct in-progress state color');
assert.match(css, /body\[data-active-view="builders"\] \.validation-focus-head h3[\s\S]{0,160}font-size: clamp\(34px, 4\.1vw, 56px\) !important/, 'Builder selected-name type should be reduced after screenshot QA');
assert.match(css, /v1\.63\.2 - Phase 31 QA correction: Builders market names must never fracture/, 'Phase 31 Builders market-name screenshot QA correction marker required');
assert.match(css, /body\[data-active-view="builders"\] \.market-toggle-grid[\s\S]{0,120}grid-template-columns: repeat\(5, minmax\(118px, 1fr\)\) !important/, 'Builder market ledger should reserve enough width to avoid fractured market names');
assert.match(css, /body\[data-active-view="builders"\] \.market-toggle strong[\s\S]{0,160}word-break: normal !important;[\s\S]{0,80}hyphens: none !important/, 'Builder market names must not break letter-by-letter');
assert.match(css, /v1\.63\.3 - Phase 31 QA correction: all five Builders markets remain visible without clipping/, 'Phase 31 Builders no-clipping market QA correction marker required');
assert.match(css, /body\[data-active-view="builders"\] \.market-toggle-grid[\s\S]{0,120}grid-template-columns: repeat\(5, minmax\(0, 1fr\)\) !important;[\s\S]{0,80}overflow-x: visible !important/, 'Builder market ledger should keep all five states visible without horizontal clipping');
assert.match(css, /v1\.63\.4 - Phase 31 QA correction: Builders market selector gets full-width control treatment/, 'Phase 31 Builders full-width market-selector QA correction marker required');
assert.match(css, /body\[data-active-view="builders"\] \.builder-ops-header[\s\S]{0,120}grid-template-columns: minmax\(0, 1fr\) !important/, 'Builder market selector should not be squeezed into a narrow side column');
assert.match(css, /body\[data-active-view="builders"\] \.builder-market-workbench[\s\S]{0,180}grid-column: 1 \/ -1 !important/, 'Builder market workbench should span the full header width');
assert.match(css, /v1\.63\.5 - Phase 31 QA correction: Builders workbench must not create dead vertical space/, 'Phase 31 Builders dead-space QA correction marker required');
assert.match(css, /body\[data-active-view="builders"\] \.builder-ops-header[\s\S]{0,220}align-content: start !important;[\s\S]{0,120}gap: clamp\(18px, 2\.8vw, 34px\) !important/, 'Builder header cadence should be tightened after screenshot QA');
assert.match(css, /v1\.63\.6 - Phase 31 hard Apple review repair: Builders mobile rows and actions must be readable, not poster UI/, 'Hard Apple review repair marker required for Builders');
assert.match(css, /--phase31-hard-repair-rule: builders-no-billboards-no-fractured-mobile-rows/, 'Hard repair rule should encode the screenshot failures');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.next-best-action[\s\S]{0,900}grid-template-columns: 96px minmax\(0, 1fr\) !important;[\s\S]{0,900}background: transparent !important;[\s\S]{0,220}box-shadow: none !important/, 'Builders next action must be a compact instruction row, not a boxed billboard');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.next-best-action strong[\s\S]{0,260}font: 650 clamp\(16px, 1\.35vw, 20px\)\/1\.28/, 'Builders next action copy must not use billboard-scale type');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.validation-actions[\s\S]{0,220}grid-template-columns: repeat\(4, minmax\(0, 1fr\)\) !important/, 'Builder action controls should be an even compact rail');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.validation-call-button\.copy-email-button[\s\S]{0,180}background: var\(--phase31-forest\) !important/, 'Draft button should be the only restrained primary action, not a giant slab');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.seller-unlock-card li[\s\S]{0,180}grid-template-columns: 34px minmax\(0, 1fr\) !important/, 'Seller gate rows should be readable mobile ledgers instead of fractured columns');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.seller-unlock-card li::before[\s\S]{0,100}counter\(seller-gate, decimal-leading-zero\)/, 'Seller gate row numbers should use calm counters');
assert.match(css, /v1\.63\.7 - Phase 31 hard Apple review repair: remove mobile artifacts from Builders actions and seller gate/, 'Second hard repair marker required for Builders mobile artifacts');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.selected-outreach-state[\s\S]{0,80}display: none !important/, 'Tiny outreach icon artifact row should not appear above the main action rail');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.validation-actions \.validation-email-status:empty[\s\S]{0,80}display: none !important/, 'Empty email status must not consume a mobile action-grid cell');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.seller-unlock-card li span\[aria-hidden="true"\][\s\S]{0,80}display: none !important/, 'Seller gate should not show orphan circle/check glyphs that fracture rows');
assert.match(css, /v1\.63\.8 - Phase 31 hard Apple review repair: Builders action rail uses four explicit columns/, 'Explicit action rail column repair marker required');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.validation-actions \.website-link[\s\S]{0,80}grid-column: 4 !important/, 'Website action must stay in the fourth column, not wrap to its own row');
assert.match(css, /v1\.63\.9 - Phase 31 hard Apple review repair: replace fragile mobile action grid with a single no-wrap rail/, 'Final no-wrap action rail repair marker required');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.validation-actions[\s\S]{0,180}display: flex !important;[\s\S]{0,80}flex-flow: row nowrap !important/, 'Builder action rail must be flex/no-wrap to prevent Website wrapping under Draft');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.validation-actions > :where\(a,button\)[\s\S]{0,180}flex: 1 1 0 !important/, 'Builder action buttons should share equal width in the no-wrap rail');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.seller-unlock-card li[\s\S]{0,260}display: flex !important;[\s\S]{0,360}font: 520 15px\/1\.28/, 'Seller gate rows should be simple readable rows, not fractured grid scraps');
assert.match(css, /v1\.63\.10 - Phase 31 hard Apple review repair: mobile queue scores must never split digits/, 'Queue score no-split repair marker required');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.queue-score[\s\S]{0,220}white-space: nowrap !important;[\s\S]{0,120}word-break: keep-all !important/, 'Builder queue scores must not split digits vertically on mobile');
assert.match(css, /body\[data-active-view="builders"\] #builder-list-panel \.queue-score b[\s\S]{0,280}font-variant-numeric: tabular-nums !important/, 'Builder queue score digits should remain stable tabular numbers');

console.log('global typography tests passed');
