// Source-backed Lee County FL resale / builder agent candidates.
// Generated from artifacts/agent-lists/fl-resale-builder/lee/lee-county-fl-resale-builder-agent-candidates.csv.
// Route stays manual_review until exact builder-tied sold property proof is attached.
export const leeCountyResaleBuilderAgents = [
  {
    "county": "Lee County, FL",
    "agentName": "Jeff Burns",
    "brokerageName": "Premier Sotheby's Int'l Realty",
    "agentPhone": "(239) 217-1713",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/jeff-burns/ghfclww/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/jeff-burns/ghfclww/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 772 Lee County sales, 298 total sales, price range $220K - $10.3M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Tiffany Packard",
    "brokerageName": "THE KEYES COMPANY",
    "agentPhone": "(239) 208-6433",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/tiffany-packard/wjc3ssj/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/tiffany-packard/wjc3ssj/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 477 Lee County sales, 195 total sales, price range $16K - $2.4M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Adolfo Diaz",
    "brokerageName": "Century 21 Sunbelt Realty",
    "agentPhone": "(239) 628-1662",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/adolfo-diaz/qjb5s8w/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/adolfo-diaz/qjb5s8w/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 381 Lee County sales, 207 total sales, price range $16K - $1.5M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Lisa Gottesman",
    "brokerageName": "EXP Realty LLC",
    "agentPhone": "(239) 766-5681",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/lisa-gottesman/y58dnlv/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/lisa-gottesman/y58dnlv/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 328 Lee County sales, 175 total sales, price range $46K - $1.8M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Todd Tooley",
    "brokerageName": "John R. Wood Properties",
    "agentPhone": "(239) 236-9694",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/todd-tooley/dw7w4ph/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/todd-tooley/dw7w4ph/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 282 Lee County sales, 146 total sales, price range $22K - $2.2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Jodie Thomas",
    "brokerageName": "RE/MAX Realty Team",
    "agentPhone": "(239) 933-6327",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/jodie-thomas/n5kxxrq/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/jodie-thomas/n5kxxrq/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 269 Lee County sales, 144 total sales, price range $32K - $660K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Katie Smith Sylvia",
    "brokerageName": "KW PEACE RIVER PARTNERS",
    "agentPhone": "(239) 360-4902",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/katie-smith-sylvia/27wm678/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/katie-smith-sylvia/27wm678/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 267 Lee County sales, 154 total sales, price range $13K - $1.6M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Pat Eberle",
    "brokerageName": "Raso Realty Inc",
    "agentPhone": "(612) 688-9677",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/pat-eberle/4gkfqhh/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/pat-eberle/4gkfqhh/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 246 Lee County sales, 143 total sales, price range $10K - $8.5M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Allan Hase",
    "brokerageName": "RE/MAX Realty Group",
    "agentPhone": "(239) 788-0456",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/allan-hase/66vbelr/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/allan-hase/66vbelr/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 209 Lee County sales, 122 total sales, price range $26K - $585K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Kyra Quarles",
    "brokerageName": "John R. Wood Properties",
    "agentPhone": "(239) 592-3028",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/kyra-quarles/zynp3xz/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/kyra-quarles/zynp3xz/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 208 Lee County sales, 108 total sales, price range $23K - $5.5M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Katrina Allison",
    "brokerageName": "ABSOLUTE EQUITY REALTY GROUP",
    "agentPhone": "(239) 291-3718",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/katrina-allison/c43xh5f/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/katrina-allison/c43xh5f/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 197 Lee County sales, 117 total sales, price range $25K - $956K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Gary Chappell",
    "brokerageName": "Royal Shell Real Estate, Inc.",
    "agentPhone": "(260) 264-8249",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/gary-chappell/59xckqn/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/gary-chappell/59xckqn/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 195 Lee County sales, 103 total sales, price range $45K - $2.7M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Carlos Diaz",
    "brokerageName": "Icon Premier Group, LLC",
    "agentPhone": "(239) 920-8162",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/carlos-diaz/qp49n6z/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/carlos-diaz/qp49n6z/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 191 Lee County sales, 355 total sales, price range $13K - $1.1M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Karen Borrelli",
    "brokerageName": "John R. Wood Properties",
    "agentPhone": "(239) 237-5156",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/karen-borrelli/8yhny32/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/karen-borrelli/8yhny32/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 184 Lee County sales, 103 total sales, price range $5K - $1.2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Danielle Meady",
    "brokerageName": "John R. Wood Properties",
    "agentPhone": "(239) 365-4528",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/danielle-meady/6zmszwt/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/danielle-meady/6zmszwt/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 182 Lee County sales, 94 total sales, price range $28K - $6.5M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Christian Loffreno",
    "brokerageName": "Loffreno Real Estate, Inc.",
    "agentPhone": "(239) 236-9022",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/christian-loffreno/cjf3kfd/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/christian-loffreno/cjf3kfd/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 178 Lee County sales, 92 total sales, price range $35K - $1.8M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Larry Hahn",
    "brokerageName": "Berkshire Hathaway Florida",
    "agentPhone": "(239) 360-6586",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/larry-hahn/mcerr6l/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/larry-hahn/mcerr6l/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 178 Lee County sales, 71 total sales, price range $215K - $1.5M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Al Ferri",
    "brokerageName": "Century 21 Selling Paradise",
    "agentPhone": "(239) 329-7733",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/al-ferri/7he7yyw/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/al-ferri/7he7yyw/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 167 Lee County sales, 98 total sales, price range $11K - $600K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Elizabeth Wilson",
    "brokerageName": "EXP Realty LLC",
    "agentPhone": "(239) 251-6184",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/elizabeth-wilson/jqshh94/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/elizabeth-wilson/jqshh94/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 156 Lee County sales, 84 total sales, price range $100K - $2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Tracey Gore",
    "brokerageName": "Loffreno Real Estate, Inc.",
    "agentPhone": "(239) 900-1645",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/tracey-gore/fnll8nr/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/tracey-gore/fnll8nr/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 155 Lee County sales, 82 total sales, price range $102K - $3.5M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Karen Montgomery",
    "brokerageName": "RE/MAX Realty Team",
    "agentPhone": "(321) 334-4719",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/karen-montgomery/qgyv3kz/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/karen-montgomery/qgyv3kz/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 150 Lee County sales, 76 total sales, price range $14K - $359K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Mary Blais",
    "brokerageName": "Rossman Realty Group Inc",
    "agentPhone": "(603) 207-3763",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/mary-blais/gflmgey/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/mary-blais/gflmgey/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 143 Lee County sales, 72 total sales, price range $66K - $1M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Edith Mausser",
    "brokerageName": "ERA Lahaina Realty",
    "agentPhone": "(239) 785-2053",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/edith-mausser/b3b3jy9/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/edith-mausser/b3b3jy9/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 137 Lee County sales, 73 total sales, price range $90K - $3M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Jerry Niesman",
    "brokerageName": "KW PEACE RIVER PARTNERS",
    "agentPhone": "(239) 291-4189",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/jerry-niesman/v4wy45d/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/jerry-niesman/v4wy45d/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 134 Lee County sales, 123 total sales, price range $11K - $1.2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Robert O'Grosky",
    "brokerageName": "Realty One Group MVP",
    "agentPhone": "(239) 268-6684",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/robert-ogrosky/6z2d8et/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/robert-ogrosky/6z2d8et/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 113 Lee County sales, 61 total sales, price range $18K - $810K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Maureen Gobbi",
    "brokerageName": "RE/MAX Trend",
    "agentPhone": "(239) 291-4359",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/maureen-gobbi/ryz3nn2/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/maureen-gobbi/ryz3nn2/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 108 Lee County sales, 57 total sales, price range $38K - $3.1M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Betty Leathers",
    "brokerageName": "Barclays Real Estate Group 1",
    "agentPhone": "(239) 341-5869",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/betty-leathers/pz5mhps/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/betty-leathers/pz5mhps/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 104 Lee County sales, 57 total sales, price range $15K - $1.8M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Alicia Galante",
    "brokerageName": "Cornerstone Coastal Properties",
    "agentPhone": "(239) 766-5129",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/alicia-galante/9jh7ll5/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/alicia-galante/9jh7ll5/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 104 Lee County sales, 53 total sales, price range $20K - $800K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Hank Bertodatto",
    "brokerageName": "Epique Realty Inc.",
    "agentPhone": "(239) 236-3827",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/hank-bertodatto/94mjb67/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "65",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/hank-bertodatto/94mjb67/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 103 Lee County sales, 62 total sales, price range $14K - $2.2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Arlete Cristina Cadore",
    "brokerageName": "Century 21 AllPoints Realty",
    "agentPhone": "(239) 788-0692",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/arlete-cristina-cadore/sdwx7k7/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/arlete-cristina-cadore/sdwx7k7/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 90 Lee County sales, 49 total sales, price range $17K - $690K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Heather Hitz PA Realtor",
    "brokerageName": "RE/MAX Realty Group",
    "agentPhone": "(239) 788-0735",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/heather-hitz-pa-realtor/hf88wy1/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/heather-hitz-pa-realtor/hf88wy1/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 88 Lee County sales, 46 total sales, price range $17K - $850K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Dan Colofranson",
    "brokerageName": "NEXT GENERATION REALTY OF MARION COUNTY",
    "agentPhone": "(239) 309-7548",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/dan-colofranson/b5rve3c/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/dan-colofranson/b5rve3c/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 82 Lee County sales, 66 total sales, price range $15K - $751K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "DeWayne Talley",
    "brokerageName": "Waterside Realty Group, Inc",
    "agentPhone": "(239) 788-1313",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/dewayne-talley/3dvv1jg/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/dewayne-talley/3dvv1jg/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 81 Lee County sales, 55 total sales, price range $186K - $1.2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Robin Sook",
    "brokerageName": "Coldwell Banker Realty - Lakes",
    "agentPhone": "(612) 712-8724",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/robin-sook/cfsev4e/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/robin-sook/cfsev4e/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 79 Lee County sales, 63 total sales, price range $29K - $1.2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Matthew Klinowski",
    "brokerageName": "Downing Frye Realty Inc.",
    "agentPhone": "(239) 345-3310",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/matthew-klinowski/3mq98je/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/matthew-klinowski/3mq98je/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 78 Lee County sales, 134 total sales, price range $275K - $2.8M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Shelley Millard",
    "brokerageName": "Realty World J. PAVICH R.E.",
    "agentPhone": "(586) 800-8952",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/shelley-millard/gr56dxz/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/shelley-millard/gr56dxz/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 71 Lee County sales, 60 total sales, price range $184K - $950K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Lynette Grout",
    "brokerageName": "John R Wood Properties",
    "agentPhone": "(239) 256-2086",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/lynette-grout/bg209fc/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/lynette-grout/bg209fc/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 68 Lee County sales, 47 total sales, price range $310K - $5M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Tim Sweeney",
    "brokerageName": "Elite Edge Fl Realty",
    "agentPhone": "(314) 501-5783",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/tim-sweeney/2vtxkrb/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/tim-sweeney/2vtxkrb/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 68 Lee County sales, 34 total sales, price range $159K - $700K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Jeff Nesbit",
    "brokerageName": "Nesbit Real Estate, Inc.",
    "agentPhone": "(239) 946-4286",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/jeff-nesbit/tb11q99/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/jeff-nesbit/tb11q99/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 64 Lee County sales, 33 total sales, price range $55K - $1.9M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Donna Barber-Dunn",
    "brokerageName": "Starlink Realty, Inc",
    "agentPhone": "(860) 383-7349",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/donna-barber-dunn/gnf88nw/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/donna-barber-dunn/gnf88nw/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 64 Lee County sales, 32 total sales, price range $228K - $705K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Sheena Reagan",
    "brokerageName": "Realty One Group MVP",
    "agentPhone": "(239) 251-5825",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/sheena-reagan/y54hl8r/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/sheena-reagan/y54hl8r/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 63 Lee County sales, 38 total sales, price range $25K - $683K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Judith Ann New",
    "brokerageName": "RE/MAX Realty Team",
    "agentPhone": "(239) 208-0061",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/judith-ann-new/cxgjlnd/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/judith-ann-new/cxgjlnd/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 61 Lee County sales, 35 total sales, price range $25K - $870K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Harriett McLean",
    "brokerageName": "Century 21 Sunbelt Realty",
    "agentPhone": "(239) 291-4100",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/harriett-mclean/fznjztt/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/harriett-mclean/fznjztt/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 53 Lee County sales, 29 total sales, price range $57K - $645K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Tara Molloy",
    "brokerageName": "Riverside Realty Group, LLC",
    "agentPhone": "(239) 310-6029",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/tara-molloy/zbrc6sw/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/tara-molloy/zbrc6sw/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 52 Lee County sales, 28 total sales, price range $135K - $1.6M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Beckee Fain",
    "brokerageName": "New Home Advantage Realty LLC",
    "agentPhone": "(239) 984-1745",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/beckee-fain/2w5m9n8/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/beckee-fain/2w5m9n8/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 50 Lee County sales, 31 total sales, price range $215K - $895K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Rob Pailes",
    "brokerageName": "SBL Realty Group, LLC",
    "agentPhone": "(239) 310-7140",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/rob-pailes/73kqjjw/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "60",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/rob-pailes/73kqjjw/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 50 Lee County sales, 20 total sales, price range $249K - $2M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Rita Oben",
    "brokerageName": "Loffreno Real Estate, Inc.",
    "agentPhone": "(239) 251-5986",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/rita-oben/bmy4l79/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "55",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/rita-oben/bmy4l79/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 45 Lee County sales, 23 total sales, price range $214K - $2.1M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Ricardo Arosemena",
    "brokerageName": "CASAMAGNA REALTY LLC",
    "agentPhone": "(754) 354-9385",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/ricardo-arosemena/s9q83p6/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "55",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/ricardo-arosemena/s9q83p6/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 43 Lee County sales, 93 total sales, price range $17K - $465K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Joe Crimaldi",
    "brokerageName": "Crimaldi and Associates, LLC",
    "agentPhone": "(239) 360-6794",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/joe-crimaldi/sjvgle5/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "55",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/joe-crimaldi/sjvgle5/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 41 Lee County sales, 131 total sales, price range $114K - $2.4M; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  },
  {
    "county": "Lee County, FL",
    "agentName": "Steve Komondorea",
    "brokerageName": "RealAmerica Realty Corp",
    "agentPhone": "(239) 237-5468",
    "agentProfileUrl": "https://www.homes.com/real-estate-agents/steve-komondorea/8z9rh11/",
    "builderProofType": "public_agent_directory_plus_new_construction_market_source",
    "builderProofUrl": "https://www.homes.com/new-homes/for-sale/lee-county-fl/",
    "confidence": "55",
    "route": "manual_review",
    "nextAction": "Call/verify whether agent works with builders buying infill/spec lots; before claiming builder connection, attach an exact sold address + builder/deed/permit proof.",
    "notes": "Generated under fl-resale-agent-builder-sourcing. This is a county agent candidate list from public business-facing Homes.com agent directory, not yet a strict outreach_ready builder-sold list. No emails/license numbers fabricated.",
    "sourceUrls": "https://www.homes.com/real-estate-agents/steve-komondorea/8z9rh11/; https://www.homes.com/real-estate-agents/lee-county-fl/; https://www.homes.com/new-homes/for-sale/lee-county-fl/; https://www.realtor.com/realestateandhomes-search/Lee-County_FL/show-recently-sold",
    "specBuilderEvidence": "Homes.com public profile reports 40 Lee County sales, 23 total sales, price range $51K - $850K; cross-check against builder/new-construction sold addresses before outreach as builder-connected."
  }
];
