// Generated from artifacts/buyer-lists/florida-tax-deed/lee/buyers.csv.
// Zero-fabrication: phone/email stay blank unless a verified public source supplies them.
// Lot size evidence comes from Lee County Parcels ArcGIS GISACRES/STATEDAREA and remains parcel-record proof, not seller-contact proof.
export const leeCountyTaxDeedBuyers = [
  {
    "leadId": "lee-fl-taxdeed-buyer-001",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ESMER MACEDO",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22ESMER+MACEDO%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "514 THOMAS AVE FORT MYERS, FL 33905",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002006, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025002010, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025002011, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "19-44-25-P1-00724.0100; 19-44-25-P1-00724.0090; 19-44-25-P2-0050D.0150",
    "folioId": "10253468; 10253467; 10252027",
    "propertyAddress": "3136 DUNBAR AVE; 3134 DUNBAR AVE; 2084 FOUNTAIN ST",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.069 ac; 0.117 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$16,018.50; $16,318.50; $20,518.50",
    "repeatBuyerCount": 3,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 3 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-002",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "EDITA COSNOTTI",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22EDITA+COSNOTTI%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "5733 SANDPIPER PLACE FORT MYERS, FL 33919",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001899, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025001962, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "12-46-24-13-00000.0640; 32-47-25-B3-03207.0090",
    "folioId": "10226104; 10288315",
    "propertyAddress": "17656 VILLAGE INLET CT; 27645 IMPERIAL RIVER RD",
    "propertyUse": "DRY/PRESERVE/NEIGHBORHOOD/INTERIOR; SINGLE FAMILY RESIDENTIAL",
    "lotSize": "0.10211202 ac; 0.350 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$21,118.50; $165,118.50",
    "repeatBuyerCount": 2,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 2 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-003",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MOHAMED J. YASIN & FEROZA YASSEN-APPADOO",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22MOHAMED+J.+YASIN+%26+FEROZA+YASSEN-APPADOO%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "3312 14TH ST. W LEHIGH ACRES, FL 33971",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002022, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025002072, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "25-43-23-C4-02298.A330; 06-46-24-07-00000.0240",
    "folioId": "10030409; 10222210",
    "propertyAddress": "2731 SANTA BARBARA BLVD N; 11220 BOMBAY LN",
    "propertyUse": "COMMERCIAL, VACANT; VACANT RESIDENTIAL",
    "lotSize": "0.098 ac; 0.107 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$4,418.50; $7,218.50",
    "repeatBuyerCount": 2,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 2 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-004",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "VVV INVESTMENTS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?inquirytype=EntityName&directionType=Initial&searchNameOrder=VVVINVESTMENTS%20L250002077650&aggregateId=flal-l25000207765-4fca03e",
    "mailingAddress": "165 10TH AVE NE NAPLES, FL 34120",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?inquirytype=EntityName&directionType=Initial&searchNameOrder=VVVINVESTMENTS%20L250002077650&aggregateId=flal-l25000207765-4fca03e; https://www.bizprofile.net/fl/naples/vvv-investments-llc; https://bisprofiles.com/fl/vvv-investments-l25000207765; https://lee.realtdm.com/public/cases/list (case 2025001944, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "30-43-24-C2-01060.0090",
    "folioId": "10521566",
    "propertyAddress": "1388 WEEPING WILLOW CT",
    "propertyUse": "SINGLE FAMILY RESIDENTIAL, LAKE",
    "lotSize": "0.045 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$130,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_confirmed; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: Florida entity registry/mirror sources confirm VVV Investments LLC, but no public business-facing phone/email/website found. Do not use attorney/clerk/platform/support or people-search contacts.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter; call only after a public/provider contact candidate is verified."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-005",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "PINES INVESTMENT INC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?inquirytype=EntityName&directionType=Initial&searchNameOrder=PINESINVESTMENT%20P190000414880&aggregateId=domp-p19000041488-a0be34",
    "mailingAddress": "12460 GREEN STONE CT FORT MYERS, FL 33913",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?inquirytype=EntityName&directionType=Initial&searchNameOrder=PINESINVESTMENT%20P190000414880&aggregateId=domp-p19000041488-a0be34; https://www.bizprofile.net/fl/fort-myers/pines-investment-inc; https://bisprofiles.com/fl/pines-investment-p19000041488; https://www.corporationwiki.com/p/34rl4s/pines-investment-inc; https://lee.realtdm.com/public/cases/list (case 2025001963, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "29-43-26-05-00055.0080",
    "folioId": "10299866",
    "propertyAddress": "13820 FIRST ST",
    "propertyUse": "SINGLE FAMILY RESIDENTIAL",
    "lotSize": "0.212 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$116,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_confirmed; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: Florida corporation registry/mirror sources confirm Pines Investment Inc, but no public business-facing phone/email/website found. Similar food/business results excluded as unrelated.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter; do not guess email/phone."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-006",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "LADY MAGICA CAPITAL INVESTMENT LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?inquirytype=EntityName&directionType=ForwardList&searchNameOrder=LADYMAGICA%20L210002248650&aggregateId=flal-l21000224865-4cbe3e1",
    "mailingAddress": "3098 BEAVER CREEK DR KISSIMMEE, FL 34746",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?inquirytype=EntityName&directionType=ForwardList&searchNameOrder=LADYMAGICA%20L210002248650&aggregateId=flal-l21000224865-4cbe3e1; https://www.bizprofile.net/fl/kissimmee/lady-magica-capital-investment; https://bisprofiles.com/fl/lady-magica-l21000224865; https://www.bizapedia.com/fl/lady-magica-capital-investment-llc.html; https://lee.realtdm.com/public/cases/list (case 2025001936, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "36-43-24-20-0000G.0040",
    "folioId": "10150100",
    "propertyAddress": "7043 NEW POST DR 4",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "0.11584022 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$62,318.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_confirmed; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: entity registry/mirror sources confirm Lady Magica Capital Investment LLC; no public business-facing phone/email/website found.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter; do not use social snippets without stronger identity/contact proof."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-007",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "KIEU GOINS",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22KIEU+GOINS%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "2466 W BAYSHORE RD #9 PALO ALTO, CA 94303",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001885, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "23-44-23-C4-01920.0050",
    "folioId": "10066995",
    "propertyAddress": "1416 SW 7TH CT",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.230 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$55,318.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-008",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "KENNETH GASTON CAGAN",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22KENNETH+GASTON+CAGAN%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "4821 SW 201ST TERRACE SOUTHWEST RANCHES, FL 33332",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001939, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "26-43-24-05-00000.3670",
    "folioId": "10141152",
    "propertyAddress": "620 FRIENDLY PL",
    "propertyUse": "MOBILE HOME SUBDIVISION",
    "lotSize": "0.098 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$55,118.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-009",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MAGALY CRUZ PINEIRO",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "Magaly Cruz",
    "contactRole": "Realtor / Sellstate 5 Star Realty",
    "phone": "+1 407-692-1401",
    "email": "magalycrealty@gmail.com",
    "website": "https://magalycruz.sellstate5starrealty.com/",
    "contactUrl": "https://www.sellstate5starrealty.com/agents/1800431/Magaly+Cruz",
    "mailingAddress": "207 ABBOTT AVE LEHIGH ACRES, FL 33936",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://www.sellstate5starrealty.com/agents/1800431/Magaly+Cruz; https://www.realestate.com.kh/international/us/567-barranger-avenue-s-lehigh-acres-fl-110104060178/; https://www.facebook.com/magaly.realtorflorida/; https://www.chamberofcommerce.com/business-directory/florida/fort-myers/industrial-real-estate-agency/2030419722-magaly-cruz; https://lee.realtdm.com/public/cases/list (case 2025002023, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "24-43-24-03-00015.0390",
    "folioId": "10138637",
    "propertyAddress": "8395 EBSON DR",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.317 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$28,818.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; public_professional_contact_verified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: public realtor/listing sources tie Magaly Cruz Pineiro/Magaly Cruz to Sellstate 5 Star Realty. Verified professional cell +1 407-692-1401; prior public listing exposes magalycrealty@gmail.com. Keep in buyerValidation until Lee County land buy box is confirmed.",
    "nextAction": "Call/SMS/email with buyer-validation opener; confirm whether she personally buys tax-deed/vacant lots or routes investor/builders."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-010",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "DUNG TRUONG",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22DUNG+TRUONG%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "2437 W CHAIN AVE ANAHEIM, CA 92804",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001978, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "03-45-26-04-00027.0110",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$23,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-011",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "JAJ DONG REAL ESTATE FUNDING LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://florida.intercreditreport.com/company/jaj-dong-real-estate-funding-llc",
    "mailingAddress": "9950 VIA SAN MARCO LOOP , FL 33905",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://florida.intercreditreport.com/company/jaj-dong-real-estate-funding-llc; https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/JAJ%20DONG%20REAL%20ESTATE%20FUNDING%20LLC; https://dos.fl.gov/sunbiz/other-services/data-downloads/; https://lee.realtdm.com/public/cases/list (case 2025001973, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "03-45-26-08-00065.0070",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$22,018.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_confirmed; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: accessible registry mirror matched JAJ Dong Real Estate Funding LLC/mailing address; no public business-facing phone/email/website found.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-012",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "CROSS COUNTRY DEVELOPMENTS LLC",
    "buyerType": "small_builder_or_developer_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/CROSS%20COUNTRY%20DEVELOPMENTS%20LLC",
    "mailingAddress": "7950 NW 53RD ST SUITE 324 DORAL, FL 33166",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/CROSS%20COUNTRY%20DEVELOPMENTS%20LLC; https://dos.fl.gov/sunbiz/other-services/data-downloads/; https://lee.realtdm.com/public/cases/list (case 2025001976, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "12-45-26-04-00033.0100",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$19,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website found; exact Sunbiz fetch hit Cloudflare challenge, not bypassed.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-013",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "EMF OPERATIONS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/EMF%20OPERATIONS%20LLC",
    "mailingAddress": "7420 NW 114 PATH DORAL, FL 33178",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/EMF%20OPERATIONS%20LLC; https://dos.fl.gov/sunbiz/other-services/data-downloads/; https://lee.realtdm.com/public/cases/list (case 2025001975, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "11-45-26-08-00080.0010",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$19,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website found; exact Sunbiz fetch hit Cloudflare challenge, not bypassed.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-014",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "LD DEVELOPMENT LLC",
    "buyerType": "small_builder_or_developer_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://florida.intercreditreport.com/company/ld-development-llc",
    "mailingAddress": "9172 COLLINS AVE APT 16 SURFSIDE , FL 33154",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://florida.intercreditreport.com/company/ld-development-llc; https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/LD%20DEVELOPMENT%20LLC; https://dos.fl.gov/sunbiz/other-services/data-downloads/; https://lee.realtdm.com/public/cases/list (case 2025002017, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "25-43-24-03-00069.003A",
    "folioId": "10140120",
    "propertyAddress": "7759 MCDANIEL DR",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.575 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$19,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_confirmed; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: registry mirror exists but address differs from captured Surfside mailing address; no public business-facing phone/email/website found.",
    "nextAction": "Human review identity/address before outreach; then manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-015",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ARJPR CONSULTING LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/ARJPR%20CONSULTING%20LLC",
    "mailingAddress": "1081 LAKE WELDONA DRIVE ORLANDO, FL 32806",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/ARJPR%20CONSULTING%20LLC; https://dos.fl.gov/sunbiz/other-services/data-downloads/; https://lee.realtdm.com/public/cases/list (case 2025000674, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "36-44-26-12-00112.0020",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$19,218.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website found; exact Sunbiz fetch hit Cloudflare challenge, not bypassed.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-016",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "DEALS ON LANDS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/DEALS%20ON%20LANDS%20LLC",
    "mailingAddress": "10312 MARCHMONT CT TAMPA, FL 33626",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/DEALS%20ON%20LANDS%20LLC; https://dos.fl.gov/sunbiz/other-services/data-downloads/; https://lee.realtdm.com/public/cases/list (case 2025002009, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "18-44-25-P4-00707.0080",
    "folioId": "10251827",
    "propertyAddress": "1945 LILLIE ST",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.140 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$19,118.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website found; direct domain dealsonlands.com did not resolve; exact Sunbiz fetch hit Cloudflare challenge, not bypassed.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-017",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "CENK HOLDINGS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/CENK%20HOLDINGS%20LLC",
    "mailingAddress": "8369 NORTHWEST 37TH PLACE SUNRISE, FL 33351",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/CENK%20HOLDINGS%20LLC; https://dos.fl.gov/sunbiz/other-services/data-downloads/; https://lee.realtdm.com/public/cases/list (case 2025001977, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "13-45-26-03-00027.0150",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$18,418.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website found; unrelated/direct cenkholdings.com result not used; exact Sunbiz fetch hit Cloudflare challenge, not bypassed.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-018",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MVP HUB LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=MVPHUBLLC",
    "mailingAddress": "5561 NW 82 AVE NA DORAL, FL 33166",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=MVPHUBLLC; https://www.bing.com/search?q=%22MVP%20HUB%20LLC%22; https://lee.realtdm.com/public/cases/list (case 2025001903, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "06-46-24-05-00000.3260",
    "folioId": "10222054",
    "propertyAddress": "326 ROSA LEE AVE",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.101 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$16,418.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; similarly named MVP businesses excluded.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-019",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ALI INVESTMENT AND MANAGEMENT GROUP LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=ALIINVESTMENTANDMANAGEMENTGROUPLLC",
    "mailingAddress": "4201 WEST BLUE HERON BOULEVARD UNIT 1 RIVERA BEACH, FL 33404",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=ALIINVESTMENTANDMANAGEMENTGROUPLLC; https://www.bing.com/search?q=%22ALI%20INVESTMENT%20AND%20MANAGEMENT%20GROUP%20LLC%22; https://lee.realtdm.com/public/cases/list (case 2025001688, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "02-44-26-12-00118.0140",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$16,118.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; unrelated Ali/marketplace results excluded.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-020",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "FLORIDA BROTHERS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=FLORIDABROTHERSLLC",
    "mailingAddress": "9800 MERLE DRIVE NORTH FORT MYERS, FL 33917",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=FLORIDABROTHERSLLC; https://www.bing.com/search?q=%22FLORIDA%20BROTHERS%20LLC%22%20%229800%20MERLE%22; https://lee.realtdm.com/public/cases/list (case 2025002018, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "34-43-24-01-00021.0100",
    "folioId": "10497224",
    "propertyAddress": "457 MONTEREY ST",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.1126 a",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$14,818.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; generic same-name businesses excluded.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-021",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "JAVIER BALZA",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22JAVIER+BALZA%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "6001 SW 70TH ST APT 201 SOUTH MIAMI, FL 33143",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001673, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Feb 10, 2026",
    "parcelId": "21-43-25-01-0000B.0190",
    "folioId": "10238494",
    "propertyAddress": "17381 FIRST ST",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.237 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$6,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-022",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "CITY FLORIDA LAND INC.",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=CITYFLORIDALANDINC",
    "mailingAddress": "address 5401 COLLINS AVENUE APT. 208 MIAMI BEACH, FL 33140,",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=CITYFLORIDALANDINC; https://www.bing.com/search?q=%22CITY%20FLORIDA%20LAND%20INC%22; https://lee.realtdm.com/public/cases/list (case 2025002032, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Feb 10, 2026",
    "parcelId": "02-44-23-C1-02654.A340",
    "folioId": "10049773",
    "propertyAddress": "624 DIPLOMAT PKWY W",
    "propertyUse": "COMMERCIAL, VACANT",
    "lotSize": "3125 sq.ft",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$5,239.31",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; unrelated city/land results excluded.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-023",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "DAYBREAK INVESTMENTS",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://businesssearch.ohiosos.gov/",
    "mailingAddress": "1172 PEACHCREEK RD DAYTON, OH 45458-3202",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://businesssearch.ohiosos.gov/; https://www.bing.com/search?q=%22DAYBREAK%20INVESTMENTS%22%20%221172%20PEACHCREEK%22; https://lee.realtdm.com/public/cases/list (case 2025001484, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "31-44-27-18-00004.0019",
    "folioId": "10442903",
    "propertyAddress": "32 COSMOPOLITAN DR 19",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "0.09612029 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$5,218.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; unrelated Daybreak Game/Foods/etc. results excluded.",
    "nextAction": "Human review entity identity, then manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-024",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "JU INVESTMENT PROPERTIES LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/CorpSearch.aspx",
    "mailingAddress": "156 LONG POND DR DRACUT MA 01826 DRACUT, MA 01826",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/CorpSearch.aspx; https://www.bing.com/search?q=%22JU%20INVESTMENT%20PROPERTIES%20LLC%22; https://lee.realtdm.com/public/cases/list (case 2025002031, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Feb 10, 2026",
    "parcelId": "17-44-27-01-00003.012D",
    "folioId": "",
    "propertyAddress": "",
    "propertyUse": "tax deed parcel; verify GIS/property appraiser before routing seller parcels",
    "lotSize": "GIS lot size pending",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$4,018.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; unrelated JU/Jacksonville University results excluded.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-025",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MATIAS INTERNATIONAL DEVELOPMENT,LLC",
    "buyerType": "small_builder_or_developer_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=MATIASINTERNATIONALDEVELOPMENTLLC",
    "mailingAddress": "4700 NW BOCA RATON BLVD STE 202 BOCA RATON, FL 33431",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults?inquiryType=EntityName&searchNameOrder=MATIASINTERNATIONALDEVELOPMENTLLC; https://www.bing.com/search?q=%22MATIAS%20INTERNATIONAL%20DEVELOPMENT%20LLC%22; https://lee.realtdm.com/public/cases/list (case 2025001697, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "02-44-23-C1-02654.A100",
    "folioId": "10049753",
    "propertyAddress": "710 DIPLOMAT PKWY W",
    "propertyUse": "COMMERCIAL, VACANT",
    "lotSize": "3125 sq.ft",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$3,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; unrelated Matias product/apparel sites excluded.",
    "nextAction": "Manual/provider skip-trace or mailed buyer-validation letter."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-026",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "WAYNE ZALESKI & WARREN DENNIS",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22WAYNE+ZALESKI+%26+WARREN+DENNIS%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "3590 EDGEWOOD AVENUE FORT MYERS, FL 33916",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002013, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "19-44-25-P4-0010B.0120",
    "folioId": "10253561",
    "propertyAddress": "ACCESS UNDETERMINED",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.290 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$3,218.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it. Lot size enriched from Lee County Parcels GIS; verify Property Appraiser record before routing seller parcels.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-027",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ARISTOCRAT ASSETS ENTERPRISE",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "contactRole": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://ecorp.azcc.gov/EntitySearch/Index",
    "mailingAddress": "975 N SILVERBELL RD #85073 TUCSON, AZ 85745",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://ecorp.azcc.gov/EntitySearch/Index; https://www.bing.com/search?q=%22ARISTOCRAT%20ASSETS%20ENTERPRISE%22; https://lee.realtdm.com/public/cases/list (case 2025002005, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "19-44-25-P1-00217.0200",
    "folioId": "10253101",
    "propertyAddress": "2989 DUNBAR AVE",
    "propertyUse": "VACANT RESIDENTIAL",
    "lotSize": "0.069 ac",
    "lotSizeSource": "Lee County Parcels ArcGIS FeatureServer (GISACRES/STATEDAREA)",
    "lotSizeSourceUrl": "https://maps.leegov.com/datasets/lee-county-parcels/about",
    "winningBid": "$2,018.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; registry_search; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Public-business OSINT 2026-07-22: no public business-facing phone/email/website/contact form found; unrelated Aristocrat gaming/motor/luggage results excluded.",
    "nextAction": "Human review entity identity, then manual/provider skip-trace or mailed buyer-validation letter."
  }
];
