// Generated from artifacts/seller-lists/pa-upset-sale/york-county/york-pa-2acre-plus-tax-deed-page-owner-runway-import.csv.
// Official York Tax Claim + York ArcGIS 2+ acre vacant/no-building candidate list; owner phone/email intentionally blank until verified.
export const pennsylvaniaYorkUpsetSaleOwnerRunway = [
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-001",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "MOWERY DANIEL B & HAILEY",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "161 DUNCAN LP, BOILING SPRINGS PA 17007-9312",
    "parcelId": "38-000-04-0013.00-00000",
    "propertyAddress": "2 CHARLES WAY",
    "propertyUse": "4.7 ac vacant/no-building parcel; class R; LUC 197; utility No Utilities",
    "lotSize": "4.7 ac",
    "acreage": 4.7,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 4.700 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-002",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "FORKER KEIRA A-TR & FORKER IRREVOCABLE RESIDENTIAL",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "280 DUNKLEBERGER RD, WILLIAMSPORT PA 17701-9292",
    "parcelId": "33-000-08-0032.00-00000",
    "propertyAddress": "OAKWOOD      OFF DR",
    "propertyUse": "3.22 ac vacant/no-building parcel; class R; LUC 100; utility No Utilities",
    "lotSize": "3.22 ac",
    "acreage": 3.22,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 3.220 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-003",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "HEARTLAND BUILDERS INC",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "3024 COLUMBIA AVE   STE 2, LANCASTER PA 17603-4011",
    "parcelId": "54-000-18-0123.00-00000",
    "propertyAddress": "ISAAC CT",
    "propertyUse": "5.68 ac vacant/no-building parcel; class R; LUC 197; utility No Utilities",
    "lotSize": "5.68 ac",
    "acreage": 5.68,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 5.680 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-004",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "MILLER JAMES P",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "1282 KLINES RUN RD, WRIGHTSVILLE PA 17368-9120",
    "parcelId": "35-000-12-0308.00-00000",
    "propertyAddress": "KLINES RUN RD",
    "propertyUse": "4.09 ac vacant/no-building parcel; class F; LUC 901; utility No Utilities",
    "lotSize": "4.09 ac",
    "acreage": 4.09,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 4.090 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-005",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "UNITED CANAL LLC",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "33 GREAT NECK RD   STE 2, GREAT NECK NY 11021-3335",
    "parcelId": "12-415-17-0027.00-00000",
    "propertyAddress": "951 ELM ST",
    "propertyUse": "3.87 ac vacant/no-building parcel; class I; LUC 500; utility All Public",
    "lotSize": "3.87 ac",
    "acreage": 3.87,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 3.870 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-006",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "LOUCKS MILL RE LP",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "1001 LOUCKS MILL RD, YORK PA 17402",
    "parcelId": "48-000-01-0008.00-00000",
    "propertyAddress": "LOUCKS MILL RD",
    "propertyUse": "5.206 ac vacant/no-building parcel; class I; LUC 500; utility All Public",
    "lotSize": "5.206 ac",
    "acreage": 5.206,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 5.206 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-007",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "NORTHERN YORK CNTY HISTORICAL & PRESERVATION SOCIETY",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "PO BOX 340, DILLSBURG PA 17019-0340",
    "parcelId": "58-000-02-0002.00-00000",
    "propertyAddress": "227 N BALTIMORE ST",
    "propertyUse": "2.55 ac vacant/no-building parcel; class E; LUC 681; utility Public Water, Public Sewer",
    "lotSize": "2.55 ac",
    "acreage": 2.55,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 2.550 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-008",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "U S HOME LLC",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "7035 ALBERT EINSTEIN DR STE 200, COLUMBIA MD 21046",
    "parcelId": "23-000-11-0024.00-00000",
    "propertyAddress": "POWDER RIDGE LN",
    "propertyUse": "30.86 ac vacant/no-building parcel; class F; LUC 900; utility No Utilities",
    "lotSize": "30.86 ac",
    "acreage": 30.86,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 30.860 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-009",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "DEPEW JEFFREY G II",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "50 PADDOCK CT, ETTERS PA 17319-9054",
    "parcelId": "39-000-31-0031.00-00000",
    "propertyAddress": "85 ROLLING HILLS CT",
    "propertyUse": "27.1 ac vacant/no-building parcel; class F; LUC 900; utility Well",
    "lotSize": "27.1 ac",
    "acreage": 27.1,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 27.100 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-2ACRE-UPSET-VAC-010",
    "state": "PA",
    "county": "York",
    "market": "York County PA - 2+ acre upset-sale runway",
    "ownerName": "SENECA RIDGE HOMEOWNERS ASSOCIATION ATTN BENNETT WILLIAMS REALTY",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "3528 CONCORD RD, YORK PA 17402",
    "parcelId": "47-000-06-0208.00-00000",
    "propertyAddress": "SENECA RIDGE DR",
    "propertyUse": "36.65 ac vacant/no-building parcel; class R; LUC 126; utility Well, Septic",
    "lotSize": "36.65 ac",
    "acreage": 36.65,
    "auctionDate": "2026-09-17",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen + 2-acre-filter",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim + York County Parcels ArcGIS",
    "buyerFit": "2+ acre lot/acreage candidate; buyer demand still must be validated before seller offer",
    "notes": "2+ acre filter; official parcel layer shows 36.650 acres, $0 building value, no residential living area/year built; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status. Phone/email intentionally blank in app until independently verified; owner row remains skip-trace/mail only. PA upset-sale status and liens must be verified before outreach.",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0 ; https://yorkcountypa.gov/528/Tax-Sale-Information ; https://yorkcountypa.gov/DocumentCenter/View/5223/Upset-Sale-Notice-2026?bidId=",
    "route": "sellerSourcingReview",
    "confidence": "medium-official-tax-claim-parcel-2acre-screen",
    "nextAction": "Verify York Tax Claim sale eligibility/date/payoff, then skip-trace or mail; phone/email stays blank until verified."
  }
];

// Generated from artifacts/seller-lists/fl-tax-deed/okaloosa/okaloosa-fl-tax-deed-land-owner-runway.csv.
// Official Okaloosa Clerk/Bid4Assets + Okaloosa Property Appraiser GIS proof; owner phone/email intentionally blank until verified.
export const okaloosaCountyTaxDeedOwnerRunway = [
  {
    "leadId": "FL-OKALOOSA-TAXDEED-VAC-001",
    "state": "FL",
    "county": "Okaloosa",
    "market": "Okaloosa County FL tax deed owner runway",
    "ownerName": "DAVID A LATHAM",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "3062 AIRPORT RD, CRESTVIEW, FL, 32539",
    "parcelId": "27-4N-22-0000-0003-0110",
    "propertyAddress": "JOHN NIX RD, CRESTVIEW, FL",
    "propertyUse": "VACANT; 5.31 ac; building value $0",
    "lotSize": "5.31 ac",
    "auctionDate": "2026-08-11",
    "daysUntilAuction": "19",
    "estimatedOpeningBid": "3007",
    "taxDelinquencyAmount": "",
    "sourceType": "official-clerk-bid4assets-tax-deed-auction + official-property-appraiser-gis-shapefile",
    "sourceUrl": "https://www.bid4assets.com/OkaloosaFLTax/listings",
    "countyPageUrl": "https://qpublic.schneidercorp.com/application.aspx?AppID=855&LayerID=15999&PageTypeID=4&PageID=7114&Q=1619219915&KeyValue=27-4N-22-0000-0003-0110",
    "sourceName": "Okaloosa Clerk Tax Deed Sales / Bid4Assets + Okaloosa Property Appraiser GIS",
    "buyerFit": "vacant/residential lot candidate; buyer demand and buildability still must be validated",
    "notes": "AuctionID 1288197; status Preview; tax deed 2026-025; certificate 2024/2333 Certificate Holder FIG 20, LLC FIG 20, LLC FBO SEC PTY Advertised; appraiser owner LATHAM DAVID A (HEIRS OF); use VACANT; APPRVAL $43,468; JUSTVAL $43,468; land $43,468; building $0; legal BEG 769 FT S & 33 FT W NE COR OF NW1/4 W640 FT. Phone/email skip-trace until independently verified. Tax deed properties are sold buyer-beware and may be redeemed before final payment.",
    "sourceUrls": "https://www.bid4assets.com/OkaloosaFLTax/listings; https://qpublic.schneidercorp.com/application.aspx?AppID=855&LayerID=15999&PageTypeID=4&PageID=7114&Q=1619219915&KeyValue=27-4N-22-0000-0003-0110",
    "route": "sellerSourcingReview",
    "confidence": "high-official-auction-appraiser-vacant-proof",
    "nextAction": "Skip-trace/mail now; verify payoff, redemption timing, title, access, utilities, and buyer fit before outreach."
  },
  {
    "leadId": "FL-OKALOOSA-TAXDEED-VAC-002",
    "state": "FL",
    "county": "Okaloosa",
    "market": "Okaloosa County FL tax deed owner runway",
    "ownerName": "THOMAS O TREADWAY AND LUCIA TREADWAY AND ALICIA FORALAN NERI",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "109 LOUISE DR, CRESTVIEW, FL, 32536",
    "parcelId": "32-3N-23-303D-0000-0110",
    "propertyAddress": "BROWNING CT, CRESTVIEW, FL 32539",
    "propertyUse": "VACANT; 0 ac; building value $0",
    "lotSize": "0 ac",
    "auctionDate": "2026-08-11",
    "daysUntilAuction": "19",
    "estimatedOpeningBid": "2933",
    "taxDelinquencyAmount": "",
    "sourceType": "official-clerk-bid4assets-tax-deed-auction + official-property-appraiser-gis-shapefile",
    "sourceUrl": "https://www.bid4assets.com/OkaloosaFLTax/listings",
    "countyPageUrl": "https://qpublic.schneidercorp.com/application.aspx?AppID=855&LayerID=15999&PageTypeID=4&PageID=7114&Q=1619219915&KeyValue=32-3N-23-303D-0000-0110",
    "sourceName": "Okaloosa Clerk Tax Deed Sales / Bid4Assets + Okaloosa Property Appraiser GIS",
    "buyerFit": "vacant/residential lot candidate; buyer demand and buildability still must be validated",
    "notes": "AuctionID 1288199; status Preview; tax deed 2026-028; certificate 2024/2468 Certificate Holder FIG 20, LLC FIG 20, LLC FBO SEC PTY Advertised; appraiser owner TREADWAY THOMAS & LUCILA; use VACANT; APPRVAL $47,080; JUSTVAL $47,080; land $47,080; building $0; legal PAGE III PH 2 S/D LOT 11. Phone/email skip-trace until independently verified. Tax deed properties are sold buyer-beware and may be redeemed before final payment.",
    "sourceUrls": "https://www.bid4assets.com/OkaloosaFLTax/listings; https://qpublic.schneidercorp.com/application.aspx?AppID=855&LayerID=15999&PageTypeID=4&PageID=7114&Q=1619219915&KeyValue=32-3N-23-303D-0000-0110",
    "route": "sellerSourcingReview",
    "confidence": "high-official-auction-appraiser-vacant-proof",
    "nextAction": "Skip-trace/mail now; verify payoff, redemption timing, title, access, utilities, and buyer fit before outreach."
  },
  {
    "leadId": "FL-OKALOOSA-TAXDEED-VAC-003",
    "state": "FL",
    "county": "Okaloosa",
    "market": "Okaloosa County FL tax deed owner runway",
    "ownerName": "JAMES BARNETT",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "2121 FISHER RIDGE RD, KENNA, WV, 25248",
    "parcelId": "15-3N-24-0000-0067-0000",
    "propertyAddress": "1886 WADSWORTH RD, BAKER, FL 32531",
    "propertyUse": "VACANT/RESD/XFOB; 1.3 ac; building value $0",
    "lotSize": "1.3 ac",
    "auctionDate": "2026-08-11",
    "daysUntilAuction": "19",
    "estimatedOpeningBid": "2781",
    "taxDelinquencyAmount": "",
    "sourceType": "official-clerk-bid4assets-tax-deed-auction + official-property-appraiser-gis-shapefile",
    "sourceUrl": "https://www.bid4assets.com/OkaloosaFLTax/listings",
    "countyPageUrl": "https://qpublic.schneidercorp.com/application.aspx?AppID=855&LayerID=15999&PageTypeID=4&PageID=7114&Q=1619219915&KeyValue=15-3N-24-0000-0067-0000",
    "sourceName": "Okaloosa Clerk Tax Deed Sales / Bid4Assets + Okaloosa Property Appraiser GIS",
    "buyerFit": "vacant/residential lot candidate; buyer demand and buildability still must be validated",
    "notes": "AuctionID 1288202; status Preview; tax deed 2026-037; certificate 2024/1574 Certificate Holder FIG 20, LLC FIG 20, LLC FBO SEC PTY Advertised; appraiser owner BARNETT JAMES; use VACANT/RESD/XFOB; APPRVAL $29,601; JUSTVAL $29,601; land $20,601; building $0; legal BEG SW COR E 1/2 OF W 1/2 OF SE 1/4 OF SW 1/4 E 50. Phone/email skip-trace until independently verified. Tax deed properties are sold buyer-beware and may be redeemed before final payment.",
    "sourceUrls": "https://www.bid4assets.com/OkaloosaFLTax/listings; https://qpublic.schneidercorp.com/application.aspx?AppID=855&LayerID=15999&PageTypeID=4&PageID=7114&Q=1619219915&KeyValue=15-3N-24-0000-0067-0000",
    "route": "sellerSourcingReview",
    "confidence": "high-official-auction-appraiser-vacant-proof",
    "nextAction": "Skip-trace/mail now; verify payoff, redemption timing, title, access, utilities, and buyer fit before outreach."
  }
];
