// Generated from artifacts/buyer-lists/florida-tax-deed/lee/buyers.csv.
// Zero-fabrication: phone/email stay blank unless a verified public source supplies them.
export const leeCountyTaxDeedBuyers = [
  {
    "leadId": "lee-fl-taxdeed-buyer-001",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ESMER MACEDO",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22ESMER+MACEDO%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "514 THOMAS AVE FORT MYERS, FL 33905",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002006, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025002010, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025002011, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "19-44-25-P1-00724.0100; 19-44-25-P1-00724.0090; 19-44-25-P2-0050D.0150",
    "winningBid": "$16,018.50; $16,318.50; $20,518.50",
    "repeatBuyerCount": 3,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 3 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-002",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "EDITA COSNOTTI",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22EDITA+COSNOTTI%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "5733 SANDPIPER PLACE FORT MYERS, FL 33919",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001899, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025001962, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "12-46-24-13-00000.0640; 32-47-25-B3-03207.0090",
    "winningBid": "$21,118.50; $165,118.50",
    "repeatBuyerCount": 2,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 2 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-003",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MOHAMED J. YASIN & FEROZA YASSEN-APPADOO",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22MOHAMED+J.+YASIN+%26+FEROZA+YASSEN-APPADOO%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "3312 14TH ST. W LEHIGH ACRES, FL 33971",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002022, doc View Recorded Tax Deed); https://lee.realtdm.com/public/cases/list (case 2025002072, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "25-43-23-C4-02298.A330; 06-46-24-07-00000.0240",
    "winningBid": "$4,418.50; $7,218.50",
    "repeatBuyerCount": 2,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 2 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-004",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "VVV INVESTMENTS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/VVV%20INVESTMENTS%20LLC",
    "mailingAddress": "165 10TH AVE NE NAPLES, FL 34120",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001944, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "30-43-24-C2-01060.0090",
    "winningBid": "$130,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-005",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "PINES INVESTMENT INC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/PINES%20INVESTMENT%20INC",
    "mailingAddress": "12460 GREEN STONE CT FORT MYERS, FL 33913",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001963, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "29-43-26-05-00055.0080",
    "winningBid": "$116,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-006",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "LADY MAGICA CAPITAL INVESTMENT LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/LADY%20MAGICA%20CAPITAL%20INVESTMENT%20LLC",
    "mailingAddress": "3098 BEAVER CREEK DR KISSIMMEE, FL 34746",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001936, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "36-43-24-20-0000G.0040",
    "winningBid": "$62,318.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-007",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "KIEU GOINS",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22KIEU+GOINS%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "2466 W BAYSHORE RD #9 PALO ALTO, CA 94303",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001885, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "23-44-23-C4-01920.0050",
    "winningBid": "$55,318.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-008",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "KENNETH GASTON CAGAN",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22KENNETH+GASTON+CAGAN%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "4821 SW 201ST TERRACE SOUTHWEST RANCHES, FL 33332",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001939, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "26-43-24-05-00000.3670",
    "winningBid": "$55,118.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-009",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MAGALY CRUZ PINEIRO",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22MAGALY+CRUZ+PINEIRO%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "207 ABBOTT AVE LEHIGH ACRES, FL 33936",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002023, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "24-43-24-03-00015.0390",
    "winningBid": "$28,818.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-010",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "DUNG TRUONG",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22DUNG+TRUONG%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "2437 W CHAIN AVE ANAHEIM, CA 92804",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001978, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "03-45-26-04-00027.0110",
    "winningBid": "$23,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-011",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "JAJ DONG REAL ESTATE FUNDING LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/JAJ%20DONG%20REAL%20ESTATE%20FUNDING%20LLC",
    "mailingAddress": "9950 VIA SAN MARCO LOOP , FL 33905",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001973, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "03-45-26-08-00065.0070",
    "winningBid": "$22,018.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-012",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "CROSS COUNTRY DEVELOPMENTS LLC",
    "buyerType": "small_builder_or_developer_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/CROSS%20COUNTRY%20DEVELOPMENTS%20LLC",
    "mailingAddress": "7950 NW 53RD ST SUITE 324 DORAL, FL 33166",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001976, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "12-45-26-04-00033.0100",
    "winningBid": "$19,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-013",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "EMF OPERATIONS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/EMF%20OPERATIONS%20LLC",
    "mailingAddress": "7420 NW 114 PATH DORAL, FL 33178",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001975, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "11-45-26-08-00080.0010",
    "winningBid": "$19,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-014",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "LD DEVELOPMENT LLC",
    "buyerType": "small_builder_or_developer_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/LD%20DEVELOPMENT%20LLC",
    "mailingAddress": "9172 COLLINS AVE APT 16 SURFSIDE , FL 33154",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002017, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "25-43-24-03-00069.003A",
    "winningBid": "$19,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-015",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ARJPR CONSULTING LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/ARJPR%20CONSULTING%20LLC",
    "mailingAddress": "1081 LAKE WELDONA DRIVE ORLANDO, FL 32806",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025000674, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "36-44-26-12-00112.0020",
    "winningBid": "$19,218.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-016",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "DEALS ON LANDS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/DEALS%20ON%20LANDS%20LLC",
    "mailingAddress": "10312 MARCHMONT CT TAMPA, FL 33626",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002009, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "18-44-25-P4-00707.0080",
    "winningBid": "$19,118.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-017",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "CENK HOLDINGS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/CENK%20HOLDINGS%20LLC",
    "mailingAddress": "8369 NORTHWEST 37TH PLACE SUNRISE, FL 33351",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001977, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "13-45-26-03-00027.0150",
    "winningBid": "$18,418.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-018",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MVP HUB LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/MVP%20HUB%20LLC",
    "mailingAddress": "5561 NW 82 AVE NA DORAL, FL 33166",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001903, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "06-46-24-05-00000.3260",
    "winningBid": "$16,418.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-019",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ALI INVESTMENT AND MANAGEMENT GROUP LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/ALI%20INVESTMENT%20AND%20MANAGEMENT%20GROUP%20LLC",
    "mailingAddress": "4201 WEST BLUE HERON BOULEVARD UNIT 1 RIVERA BEACH, FL 33404",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001688, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "02-44-26-12-00118.0140",
    "winningBid": "$16,118.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-020",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "FLORIDA BROTHERS LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/FLORIDA%20BROTHERS%20LLC",
    "mailingAddress": "9800 MERLE DRIVE NORTH FORT MYERS, FL 33917",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002018, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "34-43-24-01-00021.0100",
    "winningBid": "$14,818.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-021",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "JAVIER BALZA",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22JAVIER+BALZA%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "6001 SW 70TH ST APT 201 SOUTH MIAMI, FL 33143",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001673, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Feb 10, 2026",
    "parcelId": "21-43-25-01-0000B.0190",
    "winningBid": "$6,718.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-022",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "CITY FLORIDA LAND INC.",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/CITY%20FLORIDA%20LAND%20INC.",
    "mailingAddress": "address 5401 COLLINS AVENUE APT. 208 MIAMI BEACH, FL 33140,",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002032, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Feb 10, 2026",
    "parcelId": "02-44-23-C1-02654.A340",
    "winningBid": "$5,239.31",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-023",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "DAYBREAK INVESTMENTS",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22DAYBREAK+INVESTMENTS%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "1172 PEACHCREEK RD DAYTON, OH 45458-3202",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001484, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "31-44-27-18-00004.0019",
    "winningBid": "$5,218.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-024",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "JU INVESTMENT PROPERTIES LLC",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/JU%20INVESTMENT%20PROPERTIES%20LLC",
    "mailingAddress": "156 LONG POND DR DRACUT MA 01826 DRACUT, MA 01826",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002031, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Feb 10, 2026",
    "parcelId": "17-44-27-01-00003.012D",
    "winningBid": "$4,018.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-025",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "MATIAS INTERNATIONAL DEVELOPMENT,LLC",
    "buyerType": "small_builder_or_developer_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResults/EntityName/MATIAS%20INTERNATIONAL%20DEVELOPMENT%2CLLC",
    "mailingAddress": "4700 NW BOCA RATON BLVD STE 202 BOCA RATON, FL 33431",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025001697, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "02-44-23-C1-02654.A100",
    "winningBid": "$3,618.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-026",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "WAYNE ZALESKI & WARREN DENNIS",
    "buyerType": "individual_prior_tax_deed_buyer",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22WAYNE+ZALESKI+%26+WARREN+DENNIS%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "3590 EDGEWOOD AVENUE FORT MYERS, FL 33916",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002013, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "19-44-25-P4-0010B.0120",
    "winningBid": "$3,218.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  },
  {
    "leadId": "lee-fl-taxdeed-buyer-027",
    "state": "FL",
    "county": "Lee",
    "market": "Lee County / Fort Myers-Cape Coral-Lehigh Acres",
    "buyerName": "ARISTOCRAT ASSETS ENTERPRISE",
    "buyerType": "land_investor_or_prior_tax_deed_buyer_entity",
    "contactName": "",
    "phone": "",
    "email": "",
    "website": "",
    "contactUrl": "https://www.google.com/search?q=%22ARISTOCRAT+ASSETS+ENTERPRISE%22+Lee+County+Florida+tax+deed+buyer",
    "mailingAddress": "975 N SILVERBELL RD #85073 TUCSON, AZ 85745",
    "sourceType": "Lee RealTDM recorded tax deed / prior tax deed sale history",
    "sourceUrls": "https://lee.realtdm.com/public/cases/list (case 2025002005, doc View Recorded Tax Deed)",
    "auctionPlatform": "RealTDM / RealAuction / Lee Clerk",
    "saleDate": "Jan 13, 2026",
    "parcelId": "19-44-25-P1-00217.0200",
    "winningBid": "$2,018.50",
    "repeatBuyerCount": 1,
    "confidence": "high_prior_buyer_evidence; contact_details_unverified",
    "route": "buyerValidation",
    "notes": "Extracted from recorded tax deed OCR. 1 observed purchase(s) in sampled Jan-Feb 2026 Lee County tax deed results. No phone/email added unless public business-facing source verifies it.",
    "nextAction": "Verify Sunbiz/website contact, call/email to confirm current Lee County land/tax-deed buy box."
  }
];
