// Generated from artifacts/seller-lists/pa-upset-sale/york-county/york-pa-unique-owner-vacant-lot-candidates.csv.
// Official-source candidate list; owner phone/email intentionally blank until verified.
export const pennsylvaniaYorkUpsetSaleOwnerRunway = [
  {
    "leadId": "PA-YORK-UPSET-VAC-001",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "LIPTAK NEAL R & CHRISTA W",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "1300 STONEHENGE DR, YORK PA 17404-9033",
    "parcelId": "36-000-19-0054.00-00000",
    "propertyAddress": "35 BURNING TREE CT",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.689 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.689 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.689 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "649",
    "appraisedLand": "51110.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-002",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "HECKERT JACK E & KAREN L",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "4201 ADMIRE RD, DOVER PA 17315",
    "parcelId": "24-000-06-0035.00-00000",
    "propertyAddress": "2645 GRANDVIEW AVE",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.332 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.332 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.332 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "392",
    "appraisedLand": "36730.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-003",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "WOODLAND DEVELOPMENT INC",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "130 CARLISLE RD, HANOVER PA 17331-2400",
    "parcelId": "52-000-28-0001.00-00000",
    "propertyAddress": "15 FUHRMAN MILL RD",
    "propertyUse": "vacant residential lot / land-use 197 / $0 building value",
    "lotSize": "0.617 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.617 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.617 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "989",
    "appraisedLand": "36130.0",
    "appraisedBuilding": "0.0",
    "utility": "Public Water, Septic",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-010",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "POWELL SCOTT A",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "226 SUNSET CIR, RED LION PA 17356",
    "parcelId": "53-000-24-0115.00-00000",
    "propertyAddress": "222 SUNSET CIR",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.542 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.542 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.542 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "1000",
    "appraisedLand": "34870.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-013",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "BUCK HEATHER RENEA",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "1401 WASHINGTON POST RD, NEW BERN NC 28562-9254",
    "parcelId": "64-000-02-0106.00-00000",
    "propertyAddress": "8 JUNIOR ST",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.13 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.13 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.13 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "1092",
    "appraisedLand": "31560.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-014",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "WINTER VAUGHN W REVOCABLE TRUST OF 2013",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "980 SUMMIT CIR N, YORK PA 17403-4428",
    "parcelId": "24-000-04-0004.00-00000",
    "propertyAddress": "2811 CARLISLE RD",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.369 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.369 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.369 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "390",
    "appraisedLand": "30860.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-015",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "COLESTOCK DAVID",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "205 N 25TH ST, CAMP HILL PA 17011-3611",
    "parcelId": "27-000-05-0009.00-00000",
    "propertyAddress": "232 OAK KNOLL RD",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.365 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.365 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.365 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "474",
    "appraisedLand": "30190.0",
    "appraisedBuilding": "0.0",
    "utility": "Public Water",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-016",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "WINTER FAMILY TRUST TRUSTEE VAUGHN W WINTER REVOC TR 2013",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "980 SUMMIT CIR N, YORK PA 17403-4428",
    "parcelId": "24-000-03-0030.00-00000",
    "propertyAddress": "GRENWAY RD",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.344 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.344 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.344 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "389",
    "appraisedLand": "28340.0",
    "appraisedBuilding": "0.0",
    "utility": "Gas, Public Water",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-017",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "ANDATO LLC",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "494 WINDSOR RD, YORK PA 17402-9522",
    "parcelId": "53-000-38-0002.00-00000",
    "propertyAddress": "DAYTON CT",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.247 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.247 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.247 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "1002",
    "appraisedLand": "28090.0",
    "appraisedBuilding": "0.0",
    "utility": "Well, Septic",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-018",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "ZEIGLER KEVIN",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "PO BOX 21752, SARASOTA FL 34276-4752",
    "parcelId": "51-000-03-0084.00-00000",
    "propertyAddress": "2120 HESS RD",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.23 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.23 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.23 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "951",
    "appraisedLand": "28000.0",
    "appraisedBuilding": "0.0",
    "utility": "Gas, Public Water",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-019",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "ECKERT JOHN F III",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "816 ATLANTIC AVE, RED LION PA 17356-1516",
    "parcelId": "82-000-05-0200.00-00000",
    "propertyAddress": "ATLANTIC AVE",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.663 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.663 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.663 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "1181",
    "appraisedLand": "27830.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-020",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "HINKLE AZALEA G",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "601 EMBREEVILLE RD, DOWNINGTOWN PA 19335-3514",
    "parcelId": "48-000-16-0173.00-00000",
    "propertyAddress": "1505 HOLLYWOOD PKWY",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.321 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.321 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.321 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "sellerSourcingReview",
    "confidence": "medium",
    "taxClaimPdfPage": "914",
    "appraisedLand": "27120.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-021",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "LEIPHART GAIL A AKA GAIL A RAUHAUSER",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "350 WEST AVE, RED LION PA 17356-9284",
    "parcelId": "54-000-09-0078.00-00000",
    "propertyAddress": "WOODLAND AVE",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.525 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.525 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.525 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "1022",
    "appraisedLand": "26140.0",
    "appraisedBuilding": "0.0",
    "utility": "Gas, Public Water",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-022",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "A L W MINISTRIES INC",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "6830 CANNERY CT, SPRING GROVE PA 17362",
    "parcelId": "82-000-06-0056.00-00000",
    "propertyAddress": "249 N MAIN ST",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.158 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.158 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.158 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "1183",
    "appraisedLand": "25940.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-023",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "WALLEN CALEB JACKSON",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "2037 GLEN COVE RD, DARLINGTON MD 21034-1112",
    "parcelId": "57-000-02-0071.00-00000",
    "propertyAddress": "201 PARKE ST",
    "propertyUse": "vacant residential lot / land-use 197 / $0 building value",
    "lotSize": "0.211 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.211 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.211 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "1066",
    "appraisedLand": "25530.0",
    "appraisedBuilding": "0.0",
    "utility": "Public Water, Septic",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-024",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "CONSTELLATION ENERGY GEN LLC",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "PO BOX 5461, CHICAGO IL 60680-5461",
    "parcelId": "39-000-01-0264.00-00000",
    "propertyAddress": "CONEWAGO AVE",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.087 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.087 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.087 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "725",
    "appraisedLand": "22920.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-025",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "TOBING MULANA H L & TERESA",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "1298 W PRINCESS ST, YORK PA 17404-3447",
    "parcelId": "88-000-07-0051.00-00000",
    "propertyAddress": "1616 W POPLAR TER",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.157 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.157 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.157 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "1210",
    "appraisedLand": "22810.0",
    "appraisedBuilding": "0.0",
    "utility": "Well, Septic",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-026",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "REAM SCOTT",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "312 MAYWOOD RD, YORK PA 17402-4015",
    "parcelId": "39-000-08-0030.00-00000",
    "propertyAddress": "VISTA CIR",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.581 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.581 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.581 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "677",
    "appraisedLand": "20730.0",
    "appraisedBuilding": "0.0",
    "utility": "Well, Septic",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-027",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "KESSLER MATTHEW P",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "153 S CHARLES ST, DALLASTOWN PA 17313-2219",
    "parcelId": "56-000-04-0263.00-00000",
    "propertyAddress": "S CHARLES ST",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.121 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.121 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.121 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "1061",
    "appraisedLand": "20100.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  },
  {
    "leadId": "PA-YORK-UPSET-VAC-028",
    "state": "PA",
    "county": "York",
    "market": "York County / south-central Pennsylvania",
    "ownerName": "BONHAM JEANETTE ANN",
    "ownerPhone": "",
    "ownerEmail": "",
    "ownerMailingAddress": "158 W GAY ST, RED LION PA 17356",
    "parcelId": "82-000-03-0002.00-00000",
    "propertyAddress": "158 W GAY ST",
    "propertyUse": "vacant residential lot / land-use 100 / $0 building value",
    "lotSize": "0.107 ac",
    "auctionDate": "",
    "estimatedOpeningBid": "",
    "taxDelinquencyAmount": "",
    "sourceType": "official-tax-claim-listing + official-parcel-vacancy-screen",
    "sourceUrl": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment",
    "countyPageUrl": "https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "sourceName": "York County Tax Claim Bureau + York County ArcGIS Parcels",
    "buyerFit": "Vacant/no-building candidate, 0.107 ac; buyer demand still must be validated before seller offer.",
    "notes": "Lot size 0.107 ac. Owner contact is skip-trace/manual-review only: phone/email intentionally blank until verified. York row is a tax-claim + parcel-vacancy candidate, not a guaranteed scheduled upset-sale parcel; confirm delinquent years, payoff, notices, sale eligibility, and sale date with Tax Claim before outreach. PA upset sale risk: property may be sold subject to mortgages, municipal claims, judgments, liens, and other encumbrances; do not imply legal advice or guaranteed auction stoppage. Original note: official parcel layer shows $0 building value; no year-built field; no residential living area; delinquent-list presence does not guarantee 2026 upset-sale eligibility until Tax Claim/payoff confirms delinquent years and sale status",
    "sourceUrls": "https://yorkcountypa.gov/523/Delinquent-Tax-Information-Payment ; https://yorkcountypa.gov/DocumentCenter/View/1911/Delinquent-Tax-Claim-Listing-PDF ; https://arcweb1.ycpc.org/server/rest/services/OPEN_DATA/Parcels/MapServer/0",
    "route": "backupReview",
    "confidence": "medium-low",
    "taxClaimPdfPage": "1174",
    "appraisedLand": "18610.0",
    "appraisedBuilding": "0.0",
    "utility": "All Public",
    "nextAction": "Confirm York Tax Claim sale eligibility/date/payoff first, then skip-trace or mail; phone/email stays blank until verified."
  }
];
